
const S={data:null,subject:'biology',chapter:1,view:'home',tab:'learn'};
const PROGRESS_KEY='liam-progress',PROGRESS_SCHEMA_VERSION=2,STUDENT={name:'Liam DeVries',grade:9};
let saved={};
function nowStamp(){return new Date().toISOString().replace(/[:.]/g,'-')}
function backupRawProgress(reason,raw){try{if(raw)localStorage.setItem(`${PROGRESS_KEY}-backup-${nowStamp()}`,JSON.stringify({reason,createdAt:new Date().toISOString(),raw}))}catch(e){}}
function migrateProgress(record){let next=record&&typeof record==='object'?record:{};if(next.__schemaVersion===PROGRESS_SCHEMA_VERSION)return next;let raw='';try{raw=localStorage.getItem(PROGRESS_KEY)||''}catch(e){}backupRawProgress('automatic schema migration',raw);next={...next,__schemaVersion:PROGRESS_SCHEMA_VERSION,__student:STUDENT,__migratedAt:new Date().toISOString(),__schemaHistory:[...(next.__schemaHistory||[]),{from:next.__schemaVersion||1,to:PROGRESS_SCHEMA_VERSION,at:new Date().toISOString()}]};return next}
function loadProgress(){try{let raw=localStorage.getItem(PROGRESS_KEY);if(!raw)return migrateProgress({});let parsed=JSON.parse(raw);return migrateProgress(parsed)}catch(e){try{let raw=localStorage.getItem(PROGRESS_KEY)||'';backupRawProgress('unreadable progress preserved',raw)}catch(_){}return migrateProgress({__loadError:String(e&&e.message||e)})}}
saved=loadProgress();
const TERM_DEFS={
biology:{
biology:['The study of life and living things.','A biologist studies organisms, cells, ecosystems, heredity, evolution, and how living systems work.'],
organism:['A living thing that has all the characteristics of life.','A bacterium, oak tree, mushroom, dog, and human are all organisms.'],
organization:['The orderly structure of living things, from cells to tissues, organs, organ systems, organisms, populations, and ecosystems.','A heart cell, heart tissue, the heart, and the circulatory system show biological organization.'],
reproduction:['The process by which living things produce offspring.','Bacteria dividing and flowering plants making seeds are examples of reproduction.'],
species:['A group of similar organisms that can breed and produce fertile offspring in nature.','Different bird species may live in the same forest but reproduce within their own species.'],
growth:['An increase in living material or body size.','A seedling growing into a mature plant shows growth.'],
development:['The changes an organism goes through during its life.','A tadpole becoming a frog is development.'],
environment:['An organism’s surroundings, including living and nonliving factors.','Temperature, water, food, predators, and shelter are parts of an organism’s environment.'],
stimulus:['A change in an organism’s surroundings that causes a response.','Bright light can be a stimulus that causes pupils to get smaller.'],
response:['A reaction to a stimulus.','A plant bending toward light is a response.'],
homeostasis:['The regulation of stable internal conditions needed for survival.','Sweating helps the body maintain temperature homeostasis.'],
energy:['The ability to cause change or do work.','Cells use energy from food to build molecules, move materials, and grow.'],
adaptation:['An inherited structure, behavior, or process that helps an organism survive and reproduce.','Camouflage can be an adaptation that helps an animal avoid predators.'],
evolution:['Change in inherited traits of populations over generations.','A population becoming better suited to its environment over many generations is evolution.'],
cell:['The basic unit of structure and function in living things.','A single bacterium is one cell; plants and animals are made of many cells.'],
ecology:['The study of interactions among organisms and between organisms and their environments.','Ecology explains how wolves, deer, plants, water, and climate affect one another.'],
ecosystem:['A community of organisms and the nonliving environment they interact with.','A pond ecosystem includes fish, algae, water, sunlight, and minerals.'],
'abiotic factor':['A nonliving part of the environment that affects organisms.','Sunlight, temperature, water, and soil are abiotic factors.'],
'biotic factor':['A living or once-living part of the environment.','Plants, animals, fungi, and bacteria are biotic factors.'],
population:['All members of the same species living in the same area at the same time.','All the deer in one forest make up a deer population.'],
community:['All the populations of different species living and interacting in an area.','Trees, birds, insects, fungi, and mammals in a forest form a community.'],
DNA:['The genetic material that carries instructions for life processes.','DNA contains instructions for traits such as some eye colors or plant characteristics.'],
habitat:['The place where an organism lives and gets what it needs to survive.','A barn owl may live in grasslands, fields, and barns. That place is its habitat.'],
niche:['An organism’s role in its ecosystem, including how it gets food, uses resources, and interacts with other organisms.','A barn owl’s niche includes hunting mice at night and helping control small mammal populations.'],
symbiosis:['A close relationship between organisms of different species in which at least one organism benefits.','Ticks on deer, orchids growing on trees, and ants protecting acacia trees are symbiotic relationships.'],
mutualism:['A symbiotic relationship in which both organisms benefit.','Ants get shelter and food from an acacia tree, while the ants help protect the tree.'],
commensalism:['A symbiotic relationship in which one organism benefits and the other is not helped or harmed much.','An orchid growing on a tree gets a place to live while the tree is mostly unaffected.'],
parasitism:['A symbiotic relationship in which one organism benefits and the host is harmed.','A tick feeding on a deer benefits, while the deer loses blood and may be irritated or sick.'],
producer:['An organism that makes its own food, usually using sunlight.','Grass is a producer because it uses sunlight to make sugars.'],
autotroph:['An organism that makes its own nutrients from nonliving sources such as sunlight or chemicals.','Plants and many algae are autotrophs.'],
heterotroph:['An organism that gets energy by consuming other organisms or organic matter.','Rabbits, hawks, fungi, and humans are heterotrophs.'],
consumer:['An organism that gets energy by eating producers or other consumers.','A rabbit that eats grass and a hawk that eats a snake are consumers.'],
herbivore:['A consumer that eats plants or other producers.','A rabbit eating grass is a herbivore.'],
carnivore:['A consumer that eats animals.','A hawk that eats a snake is a carnivore.'],
omnivore:['A consumer that eats both plants and animals.','A bear that eats berries and fish is an omnivore.'],
scavenger:['A consumer that eats dead organisms.','A vulture feeding on a dead animal is a scavenger.'],
decomposer:['An organism that breaks down dead matter and returns nutrients to the ecosystem.','Fungi and bacteria decomposing leaves help recycle matter.'],
'food chain':['A simple pathway showing how energy and matter move from one organism to another.','Sun -> grass -> grasshopper -> frog shows one food chain.'],
'food web':['A network of connected food chains showing many feeding relationships in an ecosystem.','A hawk might eat mice, rabbits, frogs, and snakes, so it belongs in a food web.'],
'trophic level':['A feeding step in a food chain or energy pyramid.','Producers are the first trophic level; herbivores are usually the next level.'],
matter:['The material that makes up living and nonliving things.','Water, carbon, nitrogen, and phosphorus are matter that cycles through ecosystems.']
},
geography:{
geography:['The study of Earth’s physical features, living things, places, and how people interact with environments.','Geography explains where things are, why they are there, and how places are connected.'],
location:['The position of a place on Earth.','A school can be described by its street address, coordinates, or nearby landmarks.'],
'absolute location':['The exact position of a place, often described with latitude and longitude.','Dallas is near 32°N, 96°W.'],
'relative location':['Where a place is in relation to other places.','New Orleans is south of Baton Rouge and near the mouth of the Mississippi River.'],
hemisphere:['One half of Earth, such as Northern, Southern, Eastern, or Western Hemisphere.','The Equator divides Earth into Northern and Southern Hemispheres.'],
'grid system':['A network of latitude and longitude lines used to locate places.','A map grid helps identify a city’s exact position.'],
latitude:['Distance north or south of the Equator, measured in degrees.','A place at 30°N is north of the Equator.'],
longitude:['Distance east or west of the Prime Meridian, measured in degrees.','A place at 90°W is west of the Prime Meridian.'],
place:['A location with physical and human characteristics that make it meaningful.','A desert city has climate, landforms, buildings, roads, and cultural features.'],
region:['An area with shared physical or human characteristics.','The Midwest is a region often connected with farming and certain climate patterns.'],
'formal region':['A region defined by a common measurable trait.','A state, country, or climate zone can be a formal region.'],
'functional region':['A region organized around a central point and its connections.','A city and its suburbs can form a functional region.'],
'perceptual region':['A region based on people’s feelings or ideas about a place.','“The South” can be a perceptual region.'],
ecosystem:['A community of living things and the nonliving environment they depend on.','A coral reef ecosystem includes coral, fish, sunlight, water, and minerals.'],
movement:['The flow of people, goods, ideas, or information from place to place.','Trade routes and migration are examples of movement.'],
'human-environment interaction':['The ways people use, adapt to, and change the environment.','Irrigation, farming, roads, and dams are human-environment interactions.'],
'physical geography':['The study of Earth’s natural features and physical systems.','Mountains, rivers, climate, and vegetation are part of physical geography.'],
'human geography':['The study of people, cultures, economies, settlements, and movement across Earth.','Population density and migration are human geography topics.'],
hydrosphere:['All of Earth’s water, including oceans, rivers, lakes, ice, and water vapor.','The Pacific Ocean and polar ice are parts of the hydrosphere.'],
lithosphere:['Earth’s land and rocky outer layer.','Continents, ocean floors, and mountains are part of the lithosphere.'],
atmosphere:['The layer of gases surrounding Earth.','Weather happens in the lower atmosphere.'],
biosphere:['The part of Earth where life exists.','Forests, oceans, grasslands, and soil ecosystems are parts of the biosphere.'],
crust:['Earth’s thin, rocky outer layer.','Continents and ocean floors are part of the crust.'],
mantle:['The thick layer of hot rock beneath Earth’s crust.','Slow movement in the mantle helps move tectonic plates.'],
core:['Earth’s hot, dense center.','The core lies beneath the mantle.'],
'continental drift':['The idea that continents have slowly moved over Earth’s surface over geologic time.','Matching coastlines and fossils helped scientists think continents were once connected.'],
magma:['Melted rock beneath Earth’s surface.','Magma can rise and feed a volcano.'],
'plate tectonics':['The theory that Earth’s crust is broken into moving plates that shape landforms and oceans.','Plate movement can build mountains, cause earthquakes, and create volcanoes.'],
subduction:['A plate interaction where one plate sinks beneath another plate.','Subduction can create volcanoes and deep ocean trenches.'],
accretion:['The process of material being added to the edge of a landmass.','Sediment or crustal fragments can be added to a continent by accretion.'],
spreading:['A plate interaction where plates move apart and new crust forms.','Seafloor spreading occurs where ocean plates pull apart.'],
fold:['A bend in rock layers caused by pressure.','Folded rock layers can help form mountains.'],
fault:['A break in rock where movement occurs.','Earthquakes often happen along faults.'],
earthquake:['A sudden shaking of Earth’s crust caused by movement along a fault.','Stress from moving plates can be released as an earthquake.'],
volcano:['An opening in Earth’s crust where magma, ash, and gases can reach the surface.','A volcanic island can form when lava builds up above sea level.'],
weathering:['The process that breaks rock into smaller pieces without moving it far away.','Water freezing in cracks can cause weathering.'],
erosion:['The movement of weathered material by water, wind, ice, or gravity.','A river carrying sediment downstream is erosion.'],
loess:['Fine soil deposited by wind.','Windblown loess can create fertile soil in some regions.'],
glacier:['A large, slow-moving mass of ice.','Glaciers can carve valleys and move rock material.'],
moraine:['A ridge or pile of rock material left by a glacier.','A moraine can mark where a glacier once stopped.'],
'water cycle':['The continuous movement of water through evaporation, condensation, precipitation, runoff, and groundwater.','Water evaporates from the ocean, forms clouds, falls as rain, and returns to rivers or the sea.'],
evaporation:['The change of liquid water into water vapor.','Sunlight can cause ocean water to evaporate.'],
condensation:['The change of water vapor into liquid droplets.','Condensation forms clouds.'],
precipitation:['Water that falls from clouds as rain, snow, sleet, or hail.','Rain falling on mountains is precipitation.'],
desalination:['The process of removing salt from seawater.','Desalination can make ocean water usable, but it often requires energy and equipment.'],
groundwater:['Water stored beneath Earth’s surface in soil and rock spaces.','Wells often draw groundwater.'],
aquifer:['An underground layer of rock or sediment that stores and carries groundwater.','A community may use an aquifer as a freshwater source.'],
freshwater:['Water with very little salt, found in rivers, lakes, ice, and underground.','Freshwater is limited but essential for drinking, farming, and ecosystems.'],
'salt water':['Water containing a high amount of dissolved salts.','Most ocean water is salt water and cannot be drunk without treatment.'],
runoff:['Water that flows over land into streams, rivers, lakes, or oceans.','After heavy rain, runoff can carry sediment down a slope.']
}
};
const WEEK2_GUIDES={
biology:{2:{title:'Week 2 Biology Day: Principles of Ecology',big:'An ecosystem is a connected system where living things interact with each other and with nonliving conditions. Energy moves through feeding relationships while matter is recycled.',mastery:['biotic vs abiotic','organism -> population -> community -> ecosystem','habitat vs niche','mutualism, commensalism, and parasitism','producer, consumer, herbivore, carnivore, omnivore, scavenger, decomposer','food-chain arrows show the direction energy and matter move'],steps:[
{t:'Ecosystems: living and nonliving parts',k:'biotic factor, abiotic factor, ecosystem',v:'pond',learn:'Ecology studies interactions among organisms and between organisms and their environment. An ecosystem includes living parts, called biotic factors, and nonliving conditions, called abiotic factors. In a pond, fish, algae, insects, and bacteria are biotic. Water, rocks, sunlight, temperature, and dissolved oxygen are abiotic. Both kinds of factors matter because a change in one part of the system can affect the others.',see:['Fish, algae, insects, bacteria','Water, rocks, sunlight, temperature'],sort:{id:'biotic-abiotic-pond',prompt:'Sort these pond parts into the correct group.',groups:[{id:'biotic',label:'BIOTIC',description:'Living parts of the ecosystem'},{id:'abiotic',label:'ABIOTIC',description:'Nonliving parts of the ecosystem'}],items:[{id:'fish',label:'fish',correctGroupId:'biotic'},{id:'algae',label:'algae',correctGroupId:'biotic'},{id:'insects',label:'insects',correctGroupId:'biotic'},{id:'water',label:'water',correctGroupId:'abiotic'},{id:'rocks',label:'rocks',correctGroupId:'abiotic'},{id:'sunlight',label:'sunlight',correctGroupId:'abiotic'},{id:'dissolved-oxygen',label:'dissolved oxygen',correctGroupId:'abiotic'}]},apply:'If the pond water temperature rises, is that a biotic or abiotic change? How could it affect fish or algae?',more:'A pond is not just a list of organisms. It is a set of relationships: sunlight affects algae, algae affect oxygen, oxygen affects fish, and bacteria recycle matter.'},
{t:'Levels of ecological organization',k:'organism, population, community, ecosystem',v:'ladder',learn:'Ecologists describe living systems at different levels. One living thing is an organism. A group of the same species in one area is a population. All the different populations interacting in one area form a community. A community plus the nonliving environment is an ecosystem. The order matters because each level adds more relationships.',see:['One coyote','Coyotes in a valley','Coyotes, rabbits, grasses, hawks','Living community plus soil, water, temperature'],try:'Put these in order from smallest to largest: ecosystem, organism, population, community.',choices:[['organism -> population -> community -> ecosystem',1,'Correct. Each step adds more organisms or adds the nonliving environment.'],['organism -> community -> population -> ecosystem',0,'Population comes before community because a population is only one species.'],['ecosystem -> community -> population -> organism',0,'That is largest to smallest, not smallest to largest.']],apply:'A group of coyotes living in one valley is which level? What level includes coyotes, rabbits, grasses, hawks, soil, water, and temperature?',more:'A biological community does not include rocks, soil, water, or sunlight. Once abiotic factors are included, you are describing an ecosystem.'},
{t:'Habitat and niche',k:'habitat, niche',v:'two',learn:'Habitat means where an organism lives. Niche means how an organism lives there: how it gets food, what resources it uses, when it is active, and how it interacts with other organisms. A barn owl may have a habitat of grasslands, fields, and barns. Its niche includes hunting mice at night and nesting in quiet sheltered places.',see:['Habitat: where it lives','Niche: how it survives and interacts'],try:'Classify the statement: “A barn owl hunts mice at night.”',choices:[['Habitat',0,'That describes what the owl does and how it gets food, so it is niche.'],['Niche',1,'Right. Hunting mice at night describes the owl’s role and behavior in the ecosystem.']],apply:'Write one habitat statement and one niche statement for a frog, owl, or rabbit.',more:'Two species can share a habitat but not have the exact same niche. Different niches reduce direct competition.'},
{t:'Symbiosis: three close relationships',k:'symbiosis, mutualism, commensalism, parasitism',v:'symbiosis',learn:'Symbiosis is a close relationship between organisms of different species. In mutualism, both organisms benefit. In commensalism, one benefits and the other is not helped or harmed much. In parasitism, one benefits while the host is harmed. The key is to identify what happens to each organism.',see:['Mutualism: + / +','Commensalism: + / 0','Parasitism: + / -'],try:'A tick feeds on a deer. Which relationship is this?',choices:[['Mutualism',0,'Both organisms do not benefit. The deer is harmed.'],['Commensalism',0,'The deer is affected, so this is not commensalism.'],['Parasitism',1,'Correct. The tick benefits and the deer is harmed.']],apply:'Choose one example: ants and acacia, orchid on a tree, or tick on deer. Explain who benefits and who is harmed or unaffected.',more:'Do not memorize only examples. Ask: who benefits, who is harmed, and who is unaffected?'},
{t:'Energy roles in ecosystems',k:'producer, autotroph, heterotroph, consumer, herbivore, carnivore, omnivore, scavenger, decomposer',v:'roles',learn:'Producers, also called autotrophs, make their own nutrients, usually using sunlight. Consumers, also called heterotrophs, get energy by eating other organisms or organic matter. Herbivores eat producers, carnivores eat animals, omnivores eat both, scavengers eat dead organisms, and decomposers break down dead matter and recycle nutrients.',see:['Grass: producer','Rabbit: herbivore','Hawk: carnivore','Bear: omnivore','Vulture: scavenger','Fungus: decomposer'],try:'Which role best fits fungus breaking down dead leaves?',choices:[['Producer',0,'A producer makes its own food. Fungus gets energy from dead matter.'],['Decomposer',1,'Correct. Decomposers break down dead matter and return nutrients.'],['Herbivore',0,'A herbivore eats producers; decomposers break down dead material.']],apply:'Classify grass, rabbit, hawk, bear, vulture, and fungus by energy role.',more:'Decomposers are not optional cleanup workers. Without them, matter would remain locked in dead organisms and waste.'},
{t:'Food chains and arrow direction',k:'food chain, producer, consumer, energy, matter',v:'chain',learn:'A food chain shows one pathway for energy and matter in an ecosystem. The arrow points in the direction energy and matter move. In Sun -> grass -> grasshopper -> frog -> snake -> hawk, grass is the producer and the grasshopper is a consumer. The arrow from grasshopper to frog means energy and matter move from the grasshopper to the frog when the frog eats it.',see:['Sun','Grass','Grasshopper','Frog','Snake','Hawk'],try:'What does grasshopper -> frog mean?',choices:[['The grasshopper eats the frog.',0,'Follow the arrow direction: energy and matter move from grasshopper to frog.'],['Energy and matter move from grasshopper to frog.',1,'Yes. The frog gets energy and matter by eating the grasshopper.'],['The frog gives energy back to the grasshopper.',0,'That reverses the arrow.']],apply:'In grass -> rabbit -> fox, identify the producer and explain what happens if rabbits decrease sharply.',more:'Food-chain arrows are one of the easiest places to get mixed up. Always ask: where does energy go next?'},
{t:'Food webs are more realistic',k:'food web, food chain, ecosystem',v:'web',learn:'A food chain shows one pathway, but most organisms have more than one feeding relationship. A food web shows connected food chains. A hawk might eat a mouse, rabbit, frog, or snake. If one population changes, several other populations may be affected because the web has many connections.',see:['Grass and seeds','Grasshopper, rabbit, mouse','Frog, snake','Hawk'],try:'Why is a food web usually more realistic than one food chain?',choices:[['It shows many connected feeding relationships.',1,'Correct. Ecosystems usually have multiple feeding paths.'],['It always has fewer organisms.',0,'A web usually shows more relationships, not fewer.']],apply:'Pick one organism in a garden food web and describe two feeding connections it could have.',more:'Food webs help explain why ecosystem changes can spread in more than one direction.'},
{t:'Trophic levels and energy pyramids',k:'trophic level, producer, consumer, energy',v:'pyramid',learn:'A trophic level is a feeding step. Producers form the base because they bring energy into the living part of the ecosystem. Consumers occupy higher levels. As energy moves from one level to the next, much of it is changed to heat, so less usable energy is available at higher levels. That is why energy pyramids have a wide base and narrow top.',see:['Hawk','Snake','Rabbit','Grass'],try:'Why are producers at the base of an energy pyramid?',choices:[['They are the smallest organisms.',0,'Size is not the reason. Producers bring energy into the food system.'],['They support the energy needs of higher levels.',1,'Correct. Producers are the energy base for consumers.']],apply:'Explain why there are usually fewer top predators than producers.',more:'No math is needed here. The important idea is that usable energy decreases as it moves upward.'},
{t:'Energy flows, matter cycles',k:'energy, matter, decomposer',v:'cycle',learn:'Energy and matter behave differently in ecosystems. Energy flows through feeding relationships and is eventually lost as heat. Matter cycles. Water, carbon, nitrogen, and phosphorus are reused as organisms live, die, decompose, and become part of the environment again. Decomposers are important because they return matter to the ecosystem.',see:['Energy: one-way flow','Matter: recycled through living and nonliving parts'],try:'Which statement is correct?',choices:[['Energy cycles forever in the same way matter does.',0,'Energy flows and is lost as heat. Matter cycles.'],['Energy flows through ecosystems; matter cycles through ecosystems.',1,'Yes. That is the core idea.']],apply:'Write one sentence explaining why decomposers matter in the cycling of matter.',more:'A strong ecology answer often separates these two ideas: energy flows, matter cycles.'},
{t:'Ecosystem detective',k:'ecosystem, biotic factor, abiotic factor, producer, consumer, decomposer, food chain',v:'detective',learn:'Now use the whole chapter idea. A backyard garden includes tomato plants, bees, caterpillars, birds, earthworms, fungi, soil, water, sunlight, and air. You can describe it as an ecosystem by identifying living and nonliving parts, energy roles, feeding relationships, and what might change if one factor changes.',see:['Tomato plants','Bees and caterpillars','Birds','Earthworms and fungi','Soil, water, sunlight, air'],try:'Build a garden explanation with at least 3 biotic factors, 3 abiotic factors, 1 producer, 2 consumers, 1 decomposer, and one food chain.',evidence:true,apply:'If caterpillars fall sharply, predict one possible effect on birds and explain your evidence.',more:'Evidence can come from this one useful activity. Liam does not need a duplicate worksheet just to prove the same understanding.'},
{t:'Biology mastery check',k:'biotic factor, abiotic factor, habitat, niche, symbiosis, producer, food chain, food web, matter',v:'mastery',learn:'Use this check to show enough understanding. Aim for solid reasoning, not perfection. If one idea is shaky, review that concept and try a simpler example.',questions:['Classify rainfall as biotic or abiotic and explain why.','Put these in order: community, organism, ecosystem, population.','Is “where a rabbit lives” habitat or niche?','Is “a rabbit eats grass and hides in brush” habitat or niche?','A bee pollinates a flower while getting nectar. Which symbiosis type is this?','In grass -> rabbit -> fox, what does the arrow from rabbit to fox mean?','Why is a food web more realistic than one food chain?','What is the difference between energy flow and matter cycling?'],apply:'Write the chapter idea in your own words: an ecosystem is connected because...',more:'A successful answer should include living factors, nonliving factors, feeding relationships, energy flow, and matter cycling.'}
]}},
geography:{2:{title:'Week 2 World Geography Day: The Earth',big:'Earth is made of interacting systems. Internal forces such as plate movement and external forces such as weathering and erosion reshape the planet, while water moves through Earth in a cycle.',mastery:['hydrosphere, lithosphere, atmosphere, biosphere','core, mantle, crust','plate tectonics','internal vs external forces','weathering vs erosion','water cycle sequence','freshwater, groundwater, aquifers'],steps:[
{t:'Earth as four connected spheres',k:'hydrosphere, lithosphere, atmosphere, biosphere',v:'earth',learn:'Geographers study Earth as a system of interacting parts. The hydrosphere is Earth’s water. The lithosphere is land and rock. The atmosphere is the layer of gases around Earth. The biosphere is where life exists. These spheres interact constantly: rain falls through air, lands on rock, flows into streams, and supports plants and animals.',see:['Hydrosphere: water','Lithosphere: land and rock','Atmosphere: air','Biosphere: life'],try:'Classify Pacific Ocean, mountain, cloud-bearing air, and forest life by sphere.',choices:[['Ocean-hydrosphere, mountain-lithosphere, air-atmosphere, forest-biosphere',1,'Correct. Each example fits its Earth sphere.'],['Ocean-lithosphere, mountain-hydrosphere, air-biosphere, forest-atmosphere',0,'Try again. Match water, land, air, and life.']],apply:'Rain falls on a mountain, plants absorb water, and streams flow downslope. Which spheres are interacting?',more:'The main point is connection. Geography often asks how physical systems work together across places.'},
{t:'Inside Earth',k:'crust, mantle, core',v:'layers',learn:'Earth has internal layers. The crust is the thin rocky outer layer. Beneath it is the mantle, a thick layer of hot rock that can move slowly over long periods. The core is Earth’s hot, dense center. These layers matter because movement inside Earth helps shape the surface.',see:['Crust: thin outside','Mantle: thick hot rock','Core: hot dense center'],try:'Which layer is the thin rocky outer layer?',choices:[['Crust',1,'Correct. The crust is Earth’s outer rocky layer.'],['Mantle',0,'The mantle is below the crust.'],['Core',0,'The core is Earth’s center.']],apply:'Why does it matter that Earth has active layers beneath the surface?',more:'Do not worry about exact depths today. Know the order and the role each layer plays.'},
{t:'Plate tectonics',k:'plate tectonics, continental drift',v:'plates',learn:'Earth’s crust is broken into large moving plates. Plate tectonics explains how these plates move and shape continents, ocean basins, mountains, earthquakes, and volcanoes. Continental drift was an earlier idea that continents had moved over time; plate tectonics explains the mechanism better.',see:['Plate A moves slowly','Plate B moves slowly','Boundary changes surface features'],try:'What can moving plates create or cause?',choices:[['Mountains, earthquakes, volcanoes, and ocean features',1,'Yes. Plate movement is an internal force shaping Earth.'],['Only weather and clouds',0,'Weather is atmosphere-related. Plate movement shapes land and ocean basins.']],apply:'Explain how slow plate movement can still create major landforms over time.',more:'Plate movement is slow compared with a human life, but over geologic time it can reshape continents.'},
{t:'Plate interactions',k:'subduction, accretion, spreading',v:'boundary',learn:'Plates can interact in different ways. In subduction, one plate sinks beneath another. In accretion, material is added to the edge of a landmass. In spreading, plates move apart and new crust forms. Each interaction changes Earth’s surface differently.',see:['Subduction: one sinks','Accretion: material added','Spreading: plates separate'],try:'Which word matches “plates move apart and new crust forms”?',choices:[['Subduction',0,'Subduction means one plate sinks beneath another.'],['Spreading',1,'Correct. Spreading occurs where plates move apart.'],['Accretion',0,'Accretion means material is added to a landmass.']],apply:'Choose subduction, accretion, or spreading and describe one landform or feature it could help create.',more:'A boundary is not just a line on a map. It is a place where plate movement can build, break, or recycle crust.'},
{t:'Folds, faults, earthquakes, and volcanoes',k:'fold, fault, earthquake, volcano, magma',v:'fault',learn:'Pressure inside Earth can bend rock layers into folds or break them along faults. When rock moves suddenly along a fault, an earthquake can occur. Volcanoes form where magma reaches or nears the surface. These are internal forces because they come from energy and movement inside Earth.',see:['Fold: bent rock','Fault: broken rock with movement','Earthquake: sudden shaking','Volcano: magma reaches surface'],try:'A crack in rock where movement occurs is a...',choices:[['Fold',0,'A fold is bent rock.'],['Fault',1,'Correct. A fault is a break where movement occurs.'],['Glacier',0,'A glacier is moving ice, an external surface force.']],apply:'Write a cause/effect chain: plate movement -> stress builds -> movement along fault -> ...',more:'Internal forces can be sudden, like earthquakes, or slow, like mountain building.'},
{t:'External forces: weathering and erosion',k:'weathering, erosion, loess, glacier, moraine',v:'weathering',learn:'External forces work on Earth’s surface. Weathering breaks rock down. Erosion moves weathered material by water, wind, ice, or gravity. A freeze crack in rock is weathering. A river carrying sediment downstream is erosion. Wind can deposit loess, and glaciers can move material and leave moraines.',see:['Weathering: breaks rock','Erosion: moves sediment','Deposition: leaves material behind'],try:'A river carries sediment away from a cliff. Is that weathering or erosion?',choices:[['Weathering',0,'Weathering breaks material down. Carrying it away is erosion.'],['Erosion',1,'Correct. Movement of weathered material is erosion.']],apply:'Classify river valley, wind-blown sediment, glacier-carved land, and volcanic island as internal, external, or both.',more:'The quick test: breaking apart = weathering; carrying away = erosion.'},
{t:'What shaped this landform?',k:'internal forces, external forces, volcano, erosion, glacier',v:'landform',learn:'Many landforms are shaped by more than one process. A mountain range may begin through internal forces, then weathering and erosion change its surface. A volcanic island forms through internal forces, then waves, rain, and wind reshape it. Good geography explanations often include both origin and later change.',see:['Mountain range','Volcanic island','River valley','Glacier valley'],try:'A volcanic island with steep slopes and streams carrying sediment is shaped by...',choices:[['Only internal forces',0,'The volcano is internal, but streams carrying sediment are external erosion.'],['Internal and external forces',1,'Correct. Volcanism builds it; water and erosion reshape it.']],apply:'Pick one landform and explain what shaped it using internal/external evidence.',more:'Do not stop at naming a landform. Explain the process that created or changed it.'},
{t:'Earth’s water',k:'hydrosphere, freshwater, salt water, desalination',v:'water',learn:'About 70 percent of Earth’s surface is covered by water, but most of that water is salt water. Freshwater is limited and extremely important for people, farming, ecosystems, and cities. Desalination can remove salt from seawater, but it takes resources and is not the default solution everywhere.',see:['Most water: oceans','Limited freshwater','People and ecosystems depend on freshwater'],try:'Why is freshwater considered limited even though Earth has so much water?',choices:[['Because most water is salt water or not easy to use.',1,'Correct. The amount of usable freshwater is limited.'],['Because oceans are usually dry.',0,'Oceans hold most of Earth’s water, but it is salt water.']],apply:'Explain why a city planner must think carefully about freshwater supply.',more:'A water-rich planet can still have freshwater scarcity because location, salt, ice, pollution, and access matter.'},
{t:'The water cycle',k:'water cycle, evaporation, condensation, precipitation, runoff, groundwater',v:'cycle',learn:'The water cycle is the movement of water through Earth’s systems. Evaporation changes liquid water into vapor. Condensation forms clouds. Precipitation returns water to Earth as rain, snow, sleet, or hail. Water may collect, run off into rivers, soak into the ground as groundwater, or evaporate again.',see:['Evaporation','Condensation','Precipitation','Runoff / groundwater','Evaporation again'],try:'Put these in order: precipitation, evaporation, condensation.',choices:[['Evaporation -> condensation -> precipitation',1,'Correct. Water vapor forms clouds, then falls back to Earth.'],['Precipitation -> condensation -> evaporation',0,'Start with water changing into vapor: evaporation.']],apply:'Trace one drop of ocean water through clouds, rain, a stream, and back toward the ocean.',more:'The water cycle links hydrosphere, atmosphere, lithosphere, and biosphere.'},
{t:'Groundwater and aquifers',k:'groundwater, aquifer, freshwater',v:'aquifer',learn:'Some water soaks into the ground and becomes groundwater. An aquifer is an underground layer of rock or sediment that stores and carries groundwater. Aquifers matter because people may use them for drinking water, farming, and communities. If groundwater is used faster than it is replaced, future supply can become a problem.',see:['Rain soaks down','Groundwater fills spaces','Aquifer stores and carries water','Well draws water'],try:'What is an aquifer?',choices:[['An underground layer that stores and carries groundwater',1,'Correct. Aquifers can be important freshwater sources.'],['A cloud that makes rain',0,'Clouds are part of condensation and precipitation, not aquifers.']],apply:'Why might a town protect land above an aquifer?',more:'Groundwater is hidden, but it is still part of the hydrosphere and water cycle.'},
{t:'Earth system challenge',k:'volcano, hydrosphere, lithosphere, biosphere, weathering, erosion',v:'challenge',learn:'Use the chapter ideas together. A volcanic island has steep mountains. Heavy rain falls. Streams carry sediment to the coast. Plants grow on the slopes. This situation includes Earth spheres, internal forces, external forces, and system interactions.',try:'Identify one internal force, one external force, one hydrosphere example, one lithosphere example, one biosphere example, and how two systems interact.',evidence:true,apply:'Write your answer as a short geography explanation, not just a list.',more:'This can be saved as evidence because it asks Liam to apply several real chapter ideas together.'},
{t:'Geography mastery check',k:'hydrosphere, lithosphere, atmosphere, biosphere, plate tectonics, weathering, erosion, water cycle, aquifer',v:'mastery',learn:'Use this check to show enough understanding. A strong answer uses the right process word and gives evidence from the situation.',questions:['Classify clouds as atmosphere, hydrosphere, lithosphere, or biosphere and explain why.','Name Earth’s three internal layers from outside to inside.','What does plate tectonics explain?','What is the difference between subduction and spreading?','A rock cracks when water freezes inside it. Weathering or erosion?','A river carries sediment downstream. Weathering or erosion?','Put evaporation, condensation, and precipitation in order.','Why is usable freshwater limited?','What is an aquifer and why does it matter?'],apply:'Write the chapter idea in your own words: Earth changes because...',more:'A successful answer should include Earth spheres, plate movement, surface processes, and water movement.'}
]}}};
function save(){try{saved.__schemaVersion=PROGRESS_SCHEMA_VERSION;saved.__student=STUDENT;saved.__updatedAt=new Date().toISOString();localStorage.setItem(PROGRESS_KEY,JSON.stringify(saved))}catch(e){}}
function esc(s){return String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function course(){return S.data[S.subject]}function chap(){return course().chapters.find(c=>c.number==S.chapter)||course().chapters[0]}
function termInfo(v){let key=String(v.term||v).toLowerCase();let known=TERM_DEFS[S.subject]?.[key]||TERM_DEFS.biology[key]||TERM_DEFS.geography[key];let raw=typeof v==='object'?v.definition:'';let context=typeof v==='object'?v.context:'';let weak=!raw||raw.length<25||/^(and|or|the|a)\b/i.test(raw)||/^\W*$/.test(raw)||/\(p\.|post-|Figure \d/i.test(raw);let definition=known?known[0]:weak?`${v.term||v} is a chapter term Liam should use to explain a specific ${S.subject==='biology'?'living system, process, structure, or relationship':'place, region, pattern, map, or human-environment relationship'}.`:raw;let example=known?known[1]:context&&context!==raw?context:`Use ${v.term||v} in a real chapter example and explain why it matters.`;return {term:typeof v==='object'?v.term:v,definition,example,context:context||example}}
function appTop(){return `<div class="top"><div class="brand">🎓 Liam Learning</div><button class="navbtn ${S.view==='home'?'active':''}" onclick="goHome()">Home</button><button class="navbtn ${S.subject==='biology'&&S.view!=='home'?'active':''}" onclick="openCourse('biology')">🧪 Biology</button><button class="navbtn ${S.subject==='geography'&&S.view!=='home'?'active':''}" onclick="openCourse('geography')">🌍 World Geography</button><button class="navbtn" onclick="parentView()">Parent</button></div>`}
function routeForState(){if(S.view==='home')return '#home';if(S.view==='course')return `#course/${S.subject}`;if(S.view==='chapter'){let extra='';let c=S.data?.[S.subject]?.chapters?.find(x=>x.number==S.chapter);if((S.tab||'learn')==='learn'&&c&&guideFor(c))extra=`/${saved[`${S.subject}-${S.chapter}-guide-step`]||0}`;return `#chapter/${S.subject}/${S.chapter}/${S.tab||'learn'}${extra}`}if(S.view==='glossary')return `#glossary/${S.subject}`;if(S.view==='semester')return `#semester/${S.subject}/${S.sem||1}`;if(S.view==='parent')return '#parent';return '#home'}
function applyRoute(){let parts=(location.hash||'#home').replace(/^#/,'').split('/').filter(Boolean);let view=parts[0]||'home';if(view==='course'&&S.data[parts[1]]){S.view='course';S.subject=parts[1];S.chapter=saved[S.subject+'-current']||course().chapters[0].number;return}if(view==='chapter'&&S.data[parts[1]]){S.view='chapter';S.subject=parts[1];S.chapter=Number(parts[2])||course().chapters[0].number;S.tab=parts[3]||'learn';if(parts[4]!==undefined){saved[`${S.subject}-${S.chapter}-guide-step`]=Number(parts[4])||0;save()}return}if(view==='glossary'&&S.data[parts[1]]){S.view='glossary';S.subject=parts[1];return}if(view==='semester'&&S.data[parts[1]]){S.view='semester';S.subject=parts[1];S.sem=Number(parts[2])||1;return}if(view==='parent'){S.view='parent';return}S.view='home'}
function navigate(replace=false){let hash=routeForState();if(location.hash!==hash){history[replace?'replaceState':'pushState']({view:S.view,subject:S.subject,chapter:S.chapter,tab:S.tab,sem:S.sem},'',hash)}render(false)}
function goHome(){S.view='home';navigate()} function openCourse(id){S.subject=id; S.view='course'; const key=id+'-current'; S.chapter=saved[key]||courseById(id).chapters[0].number; navigate()} function courseById(id){return S.data[id]}
function setChapter(n){S.chapter=n; saved[S.subject+'-current']=n;save();S.view='chapter';S.tab='learn';navigate();window.scrollTo(0,0)}
function markChapter(){saved[S.subject+'-'+S.chapter+'-done']=true;if(S.subject==='biology')saved[S.subject+'-current']=window.LiamPacing?.nextValidBiologyChapter(S.chapter)||S.chapter;else saved[S.subject+'-current']=Math.min(S.chapter+1,course().chapters[course().chapters.length-1].number);save();render(false)}
function home(){let b=S.data.biology,g=S.data.geography; let bc=saved['biology-current']||b.chapters[0].number,gc=saved['geography-current']||g.chapters[0].number;let bch=b.chapters.find(x=>x.number==bc),gch=g.chapters.find(x=>x.number==gc);return `<div class="wrap"><div class="today"><div class="eyebrow" style="color:#9dd8c8">One subject at a time</div><div class="h1">Today can stay small.</div><p class="muted">Choose one course. Learn in short blocks. Stop when the learning is done.</p></div>${studentToday()}<div class="grid"><div class="card subject bio"><h2>🧪 Biology</h2><p>Current: Chapter ${bch.number} — ${esc(bch.title)}</p><p class="muted">${b.chapters.length} available chapters · Chapter 16 was unavailable in the supplied materials.</p><button class="primary" onclick="openCourse('biology')">Continue Biology</button></div><div class="card subject geo"><h2>🌍 World Geography</h2><p>Current: Chapter ${gch.number} — ${esc(gch.title)}</p><p class="muted">${g.chapters.length} chapters · complete Chapter 1–34 set.</p><button class="primary" onclick="openCourse('geography')">Continue Geography</button></div></div><div class="card"><div class="eyebrow">Week 2</div><h2>Ready subject days</h2><div class="grid">${week2HomeCard('biology',2)}${week2HomeCard('geography',2)}</div></div></div>`}
function pacingSummary(subject){return window.LiamPacing?.summary(subject,S.data[subject],saved)||null}
function studentToday(){let bio=pacingSummary('biology'),geo=pacingSummary('geography');if(!bio||!geo)return '';let today=new Date().toISOString().slice(0,10);let current=bio.subjectDates.includes(today)?bio:geo.subjectDates.includes(today)?geo:bio;let ch=current.current;return `<div class="card student-today"><div class="eyebrow">Today</div><h2>${esc(current.subject==='biology'?'Biology':'World Geography')}</h2><p>Chapter ${ch.number} — ${esc(ch.title)}</p><p class="muted">${current.subject==='biology'?'Continue the chapter until the learning is solid.':'Continue the next Geography chapter day.'} No catch-up list, no overdue pile.</p><button class="primary" onclick="S.subject='${current.subject}';setChapter(${ch.number})">${current.subject==='biology'?'Continue Chapter':'Start Today’s Lesson'}</button></div>`}
function week2HomeCard(subject,n){let c=S.data[subject],ch=c.chapters.find(x=>x.number===n),guide=WEEK2_GUIDES[subject]?.[n],done=guide?guide.steps.filter((_,i)=>saved[`${subject}-${n}-guide-done-${i}`]).length:0,status=done===0?'Ready':done===guide.steps.length?'Complete':'In progress';return `<div class="card subject ${subject==='biology'?'bio':'geo'}"><h3>${esc(c.name)}</h3><p><strong>Chapter ${n}: ${esc(ch.title)}</strong></p><p class="muted">Status: ${status} · ${done}/${guide.steps.length} blocks complete</p><button class="primary" onclick="S.subject='${subject}';setChapter(${n})">Continue ${esc(c.name)}</button></div>`}
function coursePage(){let c=course();let curr=saved[S.subject+'-current']||c.chapters[0].number;let sem1=c.chapters.filter(x=>x.semester===1),sem2=c.chapters.filter(x=>x.semester===2);return `<div class="wrap"><div class="hero"><div><div class="eyebrow">${esc(c.name)}</div><div class="h1">Course map</div><p class="muted">Every supplied chapter is visible here. Future chapters are viewable; progress is tracked separately for each course.</p><div class="actions"><button class="primary" onclick="setChapter(${curr})">Continue Chapter ${curr}</button><button class="secondary" onclick="showGlossary()">Glossary</button><button class="secondary" onclick="semesterView(1)">Semester 1 review</button><button class="secondary" onclick="semesterView(2)">Semester 2 review</button></div></div><div><img src="${c.chapters[0].cover}" alt="course textbook"></div></div>${chapterGroup('Semester 1',sem1,curr)}${chapterGroup('Semester 2',sem2,curr)}${c.missing?.length?`<div class="card" style="margin-top:18px"><strong>Source note:</strong> Chapter ${c.missing.join(', ')} was not available in the supplied Biology materials and has not been fabricated.</div>`:''}</div>`}
function chapterGroup(title,arr,curr){return `<div class="card" style="margin-top:18px"><div class="course-head"><h2>${title}</h2><span class="muted">${arr.length} chapters</span></div><div class="chapter-list">${arr.map(ch=>`<button class="chapter-link ${ch.number==curr?'current':''}" onclick="setChapter(${ch.number})"><strong>Chapter ${ch.number}</strong><small>${esc(ch.title)}</small><small>${ch.sections.length} sections · ${ch.vocabulary.length} words · ${ch.worksheet.length} worksheet items</small>${saved[S.subject+'-'+ch.number+'-done']?'<small>✓ completed</small>':'<small>Open / upcoming</small>'}</button>`).join('')}</div></div>`}
function injectTerms(text,ch){let out=esc(text);let local=[...(ch.vocabulary||[])];let defs=Object.keys(TERM_DEFS[S.subject]||{}).map(term=>({term}));let seen=new Set();let terms=[...local,...defs].filter(v=>{let k=String(v.term||'').toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>String(b.term).length-String(a.term).length);for(const v of terms){let t=String(v.term||'').trim();if(!t||t.length<3)continue;let safe=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');let re=new RegExp(`(^|[^A-Za-z0-9])(${safe})(?=$|[^A-Za-z0-9])`,'gi');out=out.replace(re,(m,p1,p2)=>`${p1}<button class="term" onclick='event.stopPropagation();termModal(${JSON.stringify(v.term)})'>${p2}</button>`)}return out}
function chapterPage(){let ch=chap(),c=course();let idx=c.chapters.findIndex(x=>x.number===ch.number);let prev=c.chapters[idx-1],next=c.chapters[idx+1];let pct=saved[S.subject+'-'+ch.number+'-done']?100:Math.min(85, Math.round((saved[S.subject+'-'+ch.number+'-progress']||0)*100));return `<div class="wrap"><div class="hero"><div><div class="eyebrow">${esc(c.name)} · Chapter ${ch.number}</div><div class="h1">${esc(ch.title)}</div><p class="muted">Learn here. The original PDF is reference material, not required reading.</p><div class="chapter-jump no-print"><label>Jump to chapter <select onchange="setChapter(Number(this.value))">${c.chapters.map(x=>`<option value="${x.number}" ${x.number===ch.number?'selected':''}>${x.number}. ${esc(x.title)}</option>`).join('')}</select></label><button class="secondary" onclick="openCourse('${S.subject}')">Browse all chapters</button></div><div class="progress"><span style="width:${pct}%"></span></div></div><img src="${ch.cover}" alt="chapter image"></div><div class="tabs no-print"><button class="tab ${S.tab==='learn'?'active':''}" onclick="tab('learn')">Learn</button><button class="tab ${S.tab==='words'?'active':''}" onclick="tab('words')">Important words</button><button class="tab ${S.tab==='notes'?'active':''}" onclick="tab('notes')">Study guide</button><button class="tab ${S.tab==='worksheet'?'active':''}" onclick="tab('worksheet')">Worksheet</button><button class="tab ${S.tab==='check'?'active':''}" onclick="tab('check')">Knowledge check</button></div><div id="tabcontent">${tabContent(ch)}</div><div class="bottom-nav no-print"><button class="secondary" ${!prev?'disabled':''} onclick="${prev?`setChapter(${prev.number})`:''}">← ${prev?'Chapter '+prev.number:'Start'}</button><button class="primary" onclick="markChapter()">${saved[S.subject+'-'+ch.number+'-done']?'✓ Chapter complete':'Mark chapter complete'}</button><button class="secondary" ${!next?'disabled':''} onclick="${next?`setChapter(${next.number})`:''}">${next?'Chapter '+next.number:'End'} →</button></div></div>`}
function tab(t){S.tab=t;navigate()}
function tabContent(ch){if(S.tab==='words')return words(ch);if(S.tab==='notes')return notes(ch);if(S.tab==='worksheet')return worksheet(ch);if(S.tab==='check')return check(ch);return learn(ch)}
function guideFor(ch){return WEEK2_GUIDES[S.subject]?.[ch.number]||null}
function learn(ch){let guide=guideFor(ch);if(guide)return guidedLesson(ch,guide);let objectives=ch.objectives?.length?`<div class="card"><h2>What you'll learn</h2>${ch.objectives.map(x=>`<p>• ${injectTerms(x,ch)}</p>`).join('')}</div>`:'';let places=ch.places?.length?`<div class="card"><h3>Places to know</h3>${ch.places.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>`:'';return `${objectives}${places}<div class="card" style="margin-top:18px"><h2>Chapter lesson</h2><p class="muted">Short blocks, definitions when you need them, and quick checks between ideas.</p>${ch.sections.map((s,si)=>`<div class="lesson-block"><div class="eyebrow">Section ${esc(s.number)}</div><h2>${injectTerms(s.title,ch)}</h2>${s.blocks.map((b,bi)=>`<p>${injectTerms(b,ch)}</p>${bi===0?conceptActivity(ch,si):''}`).join('')}${si===0?`<img class="visual" src="${ch.visual}" alt="textbook-derived visual reference">`:''}</div>`).join('')}</div>`}
function guidedLesson(ch,guide){let key=`${S.subject}-${ch.number}-guide-step`;let idx=Math.max(0,Math.min(guide.steps.length-1,Number(saved[key]||0)));let st=guide.steps[idx];let done=guide.steps.filter((_,i)=>saved[`${S.subject}-${ch.number}-guide-done-${i}`]).length;let pct=Math.round(done/guide.steps.length*100);let ready=isStepReady(st,idx);let apply=st.sort&&!ready?'<div class="locked-apply"><strong>Apply</strong><p>The written follow-up appears after the sorting activity is complete.</p></div>':`<h3>Apply</h3>${guideText(ch,idx,'apply',st.apply||'Explain this idea in your own words using evidence.')}`;return `<div class="card guided-start"><div class="eyebrow">Week 2 subject day</div><h2>${esc(guide.title)}</h2><p>${injectTerms(guide.big,ch)}</p><div class="progress"><span style="width:${pct}%"></span></div><p class="muted">${done} of ${guide.steps.length} blocks complete. Work is saved automatically.</p><div class="guide-pills">${guide.steps.map((s,i)=>`<button class="${i===idx?'current':''} ${saved[`${S.subject}-${ch.number}-guide-done-${i}`]?'done':''}" onclick="setGuideStep(${i})">${i+1}</button>`).join('')}</div></div><div class="card guide-card"><div class="eyebrow">Block ${idx+1} of ${guide.steps.length}</div><h2>${injectTerms(st.t,ch)}</h2><div class="guide-layout"><div><h3>Learn</h3><p>${injectTerms(st.learn,ch)}</p>${guideHelp(ch,st)}${guideMore(ch,st)}</div><div>${guideVisual(st)}</div></div><div class="interaction guide-try"><h3>Try</h3>${guideTry(ch,st,idx)}${apply}</div><div class="actions no-print"><button class="secondary" ${idx===0?'disabled':''} onclick="setGuideStep(${idx-1})">Previous block</button><button class="primary" ${ready?'':'disabled'} onclick="completeGuideStep()">${idx===guide.steps.length-1?'Save mastery work':'Complete block and continue'}</button><button class="secondary" ${idx===guide.steps.length-1?'disabled':''} onclick="setGuideStep(${idx+1})">Next block</button>${ready?'':'<span class="muted complete-hint">Finish the sorting activity to continue.</span>'}</div></div>`}
function guideHelp(ch,st){return `<details class="guide-details"><summary>I don't get it</summary><div class="help-grid"><div><strong>Explain it more simply</strong><p>${injectTerms(st.t,ch)} means one small idea in the chapter. Look at the example, then answer one question about it.</p></div><div><strong>Show me an example</strong><p>${injectTerms((st.see||[]).join('; ')||st.learn.split('.').slice(0,1).join('.'),ch)}</p></div><div><strong>Walk me through it</strong><p>First name the thing. Next decide what category or process it fits. Then explain the evidence that proves it.</p></div></div></details>`}
function guideMore(ch,st){return `<details class="guide-details"><summary>Tell me more</summary><p>${injectTerms(st.more||'Use the chapter words accurately, connect them to an example, and explain the evidence.',ch)}</p></details>`}
function guideVisual(st){let items=st.see||[];let cls=st.v||'cards';if(st.v==='pyramid')return `<div class="visual-box pyramid">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;if(st.v==='earth')return `<div class="visual-box earth-model">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;if(st.v==='cycle')return `<div class="visual-box cycle">${items.map(x=>`<span>${esc(x)}</span>`).join('<b>-></b>')}</div>`;if(st.v==='web')return `<div class="visual-box web">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;return `<div class="visual-box ${esc(cls)}">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`}
function isStepReady(st,idx){return !st.sort||sortingComplete(st.sort,idx)}
function sortingKey(sort,field){return `${S.subject}-${S.chapter}-sort-${sort.id}-${field}`}
function sortingPlacements(sort){return saved[sortingKey(sort,'placements')]||{}}
function sortingComplete(sort,idx){let p=sortingPlacements(sort);return sort.items.every(item=>p[item.id]===item.correctGroupId)}
function selectedSortItem(sort){return saved[sortingKey(sort,'selected')]||''}
function sortingFeedback(sort){return saved[sortingKey(sort,'feedback')]||''}
function renderSorting(sort,idx){let p=sortingPlacements(sort),selected=selectedSortItem(sort),complete=sortingComplete(sort,idx),feedback=sortingFeedback(sort);let unsorted=sort.items.filter(item=>!p[item.id]);return `<div class="sorting" role="application" aria-label="${esc(sort.prompt)}"><p>${esc(sort.prompt)}</p><div class="sort-unsorted" aria-label="Unsorted cards">${unsorted.length?unsorted.map(item=>sortCard(sort,item,selected,false)).join(''):'<p class="muted">All cards have been placed.</p>'}</div><div class="sort-zones">${sort.groups.map(group=>`<section class="sort-zone ${complete?'complete':''}" ondragover="event.preventDefault()" ondrop='dropSortCard(event,${JSON.stringify(sort.id)},${idx},${JSON.stringify(group.id)})' aria-label="${esc(group.label)} drop zone"><button class="sort-zone-head" onclick='placeSelectedSortCard(${JSON.stringify(sort.id)},${idx},${JSON.stringify(group.id)})'><strong>${esc(group.label)}</strong><small>${esc(group.description)}</small></button><div class="sort-zone-cards">${sort.items.filter(item=>p[item.id]===group.id).map(item=>sortCard(sort,item,selected,true)).join('')}</div></section>`).join('')}</div><div class="sort-actions"><button class="secondary" onclick='resetSorting(${JSON.stringify(sort.id)},${idx})'>Reset activity</button><span class="${complete?'sort-success':'sort-feedback'}">${complete?'✓ Nice work — all '+sort.items.length+' are sorted correctly.':esc(feedback||'Click a card, then click a group. You can also drag a card into a group.')}</span></div></div>`}
function sortCard(sort,item,selected,locked){let click=locked?'':`selectSortCard(${JSON.stringify(sort.id)},${JSON.stringify(item.id)})`;return `<button class="sort-card ${locked?'correct':''} ${selected===item.id?'selected':''}" draggable="${locked?'false':'true'}" ${locked?'aria-disabled="true"':''} ondragstart='dragSortCard(event,${JSON.stringify(item.id)})' onclick='${click}' onkeydown='sortCardKey(event,${JSON.stringify(sort.id)},${JSON.stringify(item.id)})'>${esc(item.label)}${locked?' <span aria-hidden="true">✓</span>':''}</button>`}
function findSort(id){let guide=guideFor(chap());return guide?.steps?.find(s=>s.sort?.id===id)?.sort}
function selectSortCard(sortId,itemId){let sort=findSort(sortId);if(!sort)return;saved[sortingKey(sort,'selected')]=itemId;saved[sortingKey(sort,'feedback')]='Choose a group for '+sort.items.find(i=>i.id===itemId).label+'.';save();render(false)}
function sortCardKey(event,sortId,itemId){if(event.key==='Enter'||event.key===' '){event.preventDefault();selectSortCard(sortId,itemId)}}
function placeSelectedSortCard(sortId,idx,groupId){let sort=findSort(sortId),itemId=sort&&selectedSortItem(sort);if(!itemId)return;placeSortCard(sort,idx,itemId,groupId)}
function placeSortCard(sort,idx,itemId,groupId){let item=sort.items.find(i=>i.id===itemId);if(!item)return;let p={...sortingPlacements(sort)};if(item.correctGroupId===groupId){p[itemId]=groupId;saved[sortingKey(sort,'placements')]=p;saved[sortingKey(sort,'selected')]='';saved[sortingKey(sort,'feedback')]='Nice. '+item.label+' is placed.'}else{saved[sortingKey(sort,'selected')]='';saved[sortingKey(sort,'feedback')]='Try again with '+item.label+'.'}saved[S.subject+'-'+S.chapter+'-progress']=Math.max(saved[S.subject+'-'+S.chapter+'-progress']||0,.15);save();render(false)}
function dragSortCard(event,itemId){event.dataTransfer.setData('text/plain',itemId)}
function dropSortCard(event,sortId,idx,groupId){event.preventDefault();let sort=findSort(sortId),itemId=event.dataTransfer.getData('text/plain');if(sort&&itemId)placeSortCard(sort,idx,itemId,groupId)}
function resetSorting(sortId,idx){let sort=findSort(sortId);if(!sort)return;delete saved[sortingKey(sort,'placements')];delete saved[sortingKey(sort,'selected')];saved[sortingKey(sort,'feedback')]='Activity reset. Try sorting the cards again.';delete saved[`${S.subject}-${S.chapter}-guide-done-${idx}`];save();render(false)}
function guideTry(ch,st,idx){if(st.sort)return renderSorting(st.sort,idx);if(st.questions)return `<div class="check-grid">${st.questions.map((q,i)=>`<label><strong>${i+1}. ${injectTerms(q,ch)}</strong><textarea data-autosave-key="${esc(guideSaveKey(idx,'q'+i))}" oninput="saveGuideText(${idx},'q${i}',this.value)" placeholder="Short answer">${esc((saved[guideSaveKey(idx,'q'+i)]||''))}</textarea></label>`).join('')}</div>`;let html=st.try?`<p>${injectTerms(st.try,ch)}</p>`:'';if(st.choices)html+=`<div class="choice-row">${st.choices.map((c,i)=>`<button class="secondary" onclick="saveGuideChoice(${idx},${i},${c[1]},${JSON.stringify(c[2])})">${esc(c[0])}</button>`).join('')}</div><div class="fb" id="guide-fb-${idx}">${saved[guideSaveKey(idx,'choiceFeedback')]?`<div class="feedback">${esc(saved[guideSaveKey(idx,'choiceFeedback')])}</div>`:''}</div>`;if(st.evidence)html+=`<div class="evidence-badge">Saved as evidence when you write and complete this block.</div>`;return html}
function guideText(ch,idx,field,prompt){return `<label class="activity-response"><span>${injectTerms(prompt,ch)}</span><textarea data-autosave-key="${esc(guideSaveKey(idx,field))}" oninput='saveGuideText(${idx},${JSON.stringify(field)},this.value)' placeholder="Write here. This saves automatically.">${esc(saved[guideSaveKey(idx,field)]||'')}</textarea><small>Saved automatically.</small></label>`}
function guideSaveKey(idx,field){return `${S.subject}-${S.chapter}-guide-${idx}-${field}`}
function saveGuideText(idx,field,value){saved[guideSaveKey(idx,field)]=value;saved[S.subject+'-'+S.chapter+'-progress']=Math.max(saved[S.subject+'-'+S.chapter+'-progress']||0,.25);save()}
function saveGuideChoice(idx,i,ok,feedback){saved[guideSaveKey(idx,'choice')]=i;saved[guideSaveKey(idx,'choiceOk')]=!!ok;saved[guideSaveKey(idx,'choiceFeedback')]=feedback;save();let el=document.getElementById(`guide-fb-${idx}`);if(el)el.innerHTML=`<div class="feedback ${ok?'':'warn'}">${esc(feedback)}</div>`}
function setGuideStep(i){let guide=guideFor(chap());let key=`${S.subject}-${S.chapter}-guide-step`;saved[key]=Math.max(0,Math.min(guide.steps.length-1,i));save();navigate();window.scrollTo(0,0)}
function completeGuideStep(){let guide=guideFor(chap());let key=`${S.subject}-${S.chapter}-guide-step`;let idx=Math.max(0,Math.min(guide.steps.length-1,Number(saved[key]||0)));let st=guide.steps[idx];if(!isStepReady(st,idx)){saved[sortingKey(st.sort,'feedback')]='Finish sorting all cards correctly before continuing.';save();render(false);return}saved[`${S.subject}-${S.chapter}-guide-done-${idx}`]=true;if(st.evidence||st.questions||st.sort)saved[`${S.subject}-${S.chapter}-evidence-${idx}`]=new Date().toISOString();saved[S.subject+'-'+S.chapter+'-progress']=Math.max(saved[S.subject+'-'+S.chapter+'-progress']||0,(idx+1)/guide.steps.length);if(idx<guide.steps.length-1)saved[key]=idx+1;save();navigate();window.scrollTo(0,0)}
function conceptActivity(ch,si){let v=ch.vocabulary[si%Math.max(1,ch.vocabulary.length)];if(!v)return '';let info=termInfo(v);let subject=S.subject;let title=subject==='biology'?'Science quick activity':'Map thinking quick activity';let prompt=subject==='biology'?`Use ${info.term} to make a prediction or explain cause and effect.`:`Use ${info.term} to explain a place, region, movement, or human-environment decision.`;let choices=subject==='biology'?[`Connect ${info.term} to evidence from the living system.`,`Memorize ${info.term} without an example.`,`Ignore what happens in the organism or process.`]:[`Connect ${info.term} to a map, place, or spatial pattern.`,`Describe the place without location clues.`,`Ignore physical and human geography.`];let key=`${S.subject}-${ch.number}-activity-${si}`;let value=saved[key]||'';return `<div class="interaction"><strong>${title}</strong><p>${esc(prompt)}</p><div class="choice-row">${choices.map((choice,i)=>`<button class="secondary" onclick="showActivityFeedback(this,${i===0},${JSON.stringify(info.term)},${JSON.stringify(info.definition)},${JSON.stringify(info.example)})">${esc(choice)}</button>`).join('')}</div><div class="mini-visual ${subject==='biology'?'bio-mini':'geo-mini'}">${miniVisual(ch,info)}</div><label class="activity-response"><span>Your answer</span><textarea data-autosave-key="${esc(key)}" oninput="saveActivity(${si},this.value)" placeholder="${subject==='biology'?'Make a prediction, then explain the evidence.':'Explain the map/place pattern using evidence.'}">${esc(value)}</textarea><small>Saved automatically.</small></label><div class="fb"></div></div>`}
function saveActivity(i,v){saved[`${S.subject}-${S.chapter}-activity-${i}`]=v;saved[S.subject+'-'+S.chapter+'-progress']=Math.max(saved[S.subject+'-'+S.chapter+'-progress']||0,.2);save()}
function miniVisual(ch,info){if(S.subject==='biology')return `<span>Observe</span><b>→</b><span>${esc(info.term)}</span><b>→</b><span>Predict</span><b>→</b><span>Explain with evidence</span>`;return `<span>Where?</span><b>→</b><span>${esc(info.term)}</span><b>→</b><span>Pattern</span><b>→</b><span>Why there?</span>`}
function showActivityFeedback(btn,ok,term,def,example){btn.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('picked'));btn.classList.add('picked');btn.closest('.interaction').querySelector('.fb').innerHTML=ok?`<div class="feedback"><strong>${esc(term)}</strong>: ${esc(def)}<br>${esc(example)}</div>`:`<div class="feedback warn"><strong>Try again.</strong> A good answer connects the term to evidence and a real example.</div>`}
function words(ch){return `<div class="card"><h2>Important words</h2><p class="muted">Click any word to see what it means, context, and an example from the chapter.</p><div class="glossary-grid">${ch.vocabulary.map(v=>{let info=termInfo(v);return `<button class="glossary-item" onclick='termModal(${JSON.stringify(v.term)})'><strong>${esc(info.term)}</strong><div class="muted" style="margin-top:6px">${esc(info.definition.slice(0,150))}${info.definition.length>150?'…':''}</div></button>`}).join('')}</div></div>`}
function termModal(term){let v=chap().vocabulary.find(x=>x.term===term) || Object.values(S.data).flatMap(c=>c.chapters).flatMap(c=>c.vocabulary).find(x=>x.term===term) || (TERM_DEFS[S.subject]?.[String(term).toLowerCase()]?{term}:null);if(!v)return;let info=termInfo(v);document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><div class="eyebrow">Important word</div><h2>${esc(info.term)}</h2><h3>What it means</h3><p>${esc(info.definition)}</p><h3>Example</h3><p>${esc(info.example)}</p><h3>In the chapter</h3><p>${esc(info.context)}</p><div class="interaction"><strong>Check yourself</strong><p>Can you explain this term in your own words and give one example?</p></div></div></div>`)}
function notes(ch){let guide=guideFor(ch);if(guide)return guideNotes(ch,guide);return `<div class="grid"><div class="card"><h2>Study guide</h2><h3>Big ideas</h3>${ch.objectives.map(x=>`<p>• ${injectTerms(x,ch)}</p>`).join('')}<h3>Important words</h3>${ch.vocabulary.slice(0,12).map(x=>`<button class="term" onclick='termModal(${JSON.stringify(x.term)})'>${esc(x.term)}</button> `).join('')}<h3>Know this</h3>${ch.vocabulary.slice(0,6).map(v=>{let i=termInfo(v);return `<p>• <strong>${esc(i.term)}</strong>: ${esc(i.definition)}</p>`}).join('')}<h3>Be able to explain</h3>${ch.sections.map(s=>`<p>• ${injectTerms(s.title,ch)}</p>`).join('')}<h3>Be able to apply</h3><p>${S.subject==='biology'?'Use evidence to classify, predict, sequence, or explain a biological process.':'Use map evidence to explain location, region, climate, population, movement, or human-environment interaction.'}</p></div><div class="card"><h2>Chapter notes</h2>${ch.sections.map(s=>`<h3>${injectTerms(s.title,ch)}</h3><p>${injectTerms((s.blocks||[]).slice(0,2).join(' '),ch)}</p>`).join('')}</div></div>`}
function guideNotes(ch,guide){let terms=guide.steps.flatMap(s=>String(s.k||'').split(',').map(x=>x.trim()).filter(Boolean));let seen=new Set();terms=terms.filter(t=>{let k=t.toLowerCase();if(seen.has(k))return false;seen.add(k);return true});return `<div class="grid"><div class="card"><h2>Study guide</h2><h3>Big idea</h3><p>${injectTerms(guide.big,ch)}</p><h3>Important words</h3>${terms.map(t=>`<button class="term" onclick='termModal(${JSON.stringify(t)})'>${esc(t)}</button> `).join('')}<h3>Know this</h3>${guide.mastery.map(x=>`<p>• ${injectTerms(x,ch)}</p>`).join('')}<h3>Understand this</h3>${guide.steps.slice(0,-1).map(s=>`<p>• ${injectTerms(s.learn.split('.')[0]+'.',ch)}</p>`).join('')}<h3>Be able to apply</h3><p>${S.subject==='biology'?'Classify ecosystem parts, interpret feeding relationships, and explain how a change in one factor affects others.':'Use Earth-system evidence to explain spheres, landform changes, plate processes, weathering, erosion, and water movement.'}</p></div><div class="card"><h2>Chapter notes</h2>${guide.steps.slice(0,-1).map(s=>`<h3>${injectTerms(s.t,ch)}</h3><p>${injectTerms(s.learn,ch)}</p><p class="muted">${injectTerms(s.more||'',ch)}</p>`).join('')}</div></div>`}
function worksheet(ch){let key=`${S.subject}-${ch.number}-worksheet`;let vals=saved[key]||{};return `<div class="card"><div class="actions no-print"><button class="primary" onclick="exportWorksheet('blank')">Export blank PDF</button><button class="primary" onclick="exportWorksheet('completed')">Export completed PDF</button><button class="secondary" onclick="window.print()">Print / Save PDF</button><button class="secondary" onclick="exportWorksheet('key')">Parent answer key PDF</button></div><h1>${esc(course().name)} Chapter ${ch.number} Worksheet</h1><p>Student: Liam &nbsp;&nbsp; Grade: 9 &nbsp;&nbsp; Date: ${new Date().toLocaleDateString()}</p>${worksheetItems(ch).map((q,i)=>`<div class="worksheet-item ${esc(q.type)}"><div class="eyebrow">${esc(questionLabel(q.type))}</div><strong>${i+1}. ${injectTerms(q.prompt,ch)}</strong>${worksheetControl(q,i,vals[i]||'')}</div>`).join('')}</div>`}
function worksheetItems(ch){let guide=guideFor(ch);if(guide)return guideWorksheet(ch,guide);let base=(ch.worksheet||[]).slice(0,10);let terms=(ch.vocabulary||[]).slice(0,4).map((v,i)=>({type:i%2?'matching':'definition',prompt:`${i%2?'Match or connect':'Define'} ${v.term} using a chapter example.`,answer:termInfo(v).definition}));let scenario={type:S.subject==='biology'?'scenario':'map-analysis',prompt:S.subject==='biology'?`Use evidence from ${ch.title} to make a prediction about a living system, process, or experiment.`:`Use evidence from ${ch.title} to explain a place, region, climate, population pattern, or human-environment decision.`,answer:'Answer should use accurate chapter vocabulary and explain the reasoning with evidence.'};let varied=[...terms,scenario,...base].slice(0,14);return varied}
function guideWorksheet(ch,guide){if(S.subject==='biology')return [
{type:'classification',prompt:'Sort pond parts into biotic and abiotic: fish, algae, insects, water, rocks, sunlight, dissolved oxygen.',answer:'Biotic: fish, algae, insects. Abiotic: water, rocks, sunlight, dissolved oxygen.'},
{type:'sequence',prompt:'Put the organization levels in order from smallest to largest: ecosystem, population, organism, community.',answer:'organism -> population -> community -> ecosystem.'},
{type:'matching',prompt:'Match habitat and niche to these owl statements: lives in grasslands and barns; hunts mice at night.',answer:'Habitat: lives in grasslands and barns. Niche: hunts mice at night.'},
{type:'classification',prompt:'Classify each symbiosis example: ants/acacia, orchid/tree, tick/deer.',answer:'Ants/acacia: mutualism. Orchid/tree: commensalism. Tick/deer: parasitism.'},
{type:'matching',prompt:'Classify grass, rabbit, hawk, bear, vulture, and fungus by energy role.',answer:'Grass producer; rabbit herbivore; hawk carnivore; bear omnivore; vulture scavenger; fungus decomposer.'},
{type:'diagram',prompt:'In Sun -> grass -> grasshopper -> frog -> snake -> hawk, identify the producer, first consumer, and what grasshopper -> frog means.',answer:'Producer: grass. First consumer: grasshopper. Arrow means energy and matter move from grasshopper to frog.'},
{type:'scenario',prompt:'If rabbits decrease sharply in grass -> rabbit -> fox, predict what may happen to foxes and explain why.',answer:'Foxes may decrease or need other food because rabbits are an energy/matter source.'},
{type:'explain',prompt:'Explain why energy flows through ecosystems but matter cycles.',answer:'Energy moves through feeding relationships and is lost as heat; matter such as water and nutrients is recycled.'},
{type:'scenario',prompt:'Garden evidence: name 3 biotic factors, 3 abiotic factors, 1 producer, 2 consumers, 1 decomposer, and one food chain.',answer:'Accept accurate garden examples such as tomato plants, bees, caterpillars; soil, water, sunlight; tomato producer; caterpillar/bird consumers; fungus decomposer; tomato -> caterpillar -> bird.'}
];return [
{type:'classification',prompt:'Classify Pacific Ocean, mountain, cloud-bearing air, and forest life by Earth sphere.',answer:'Hydrosphere, lithosphere, atmosphere, biosphere.'},
{type:'diagram',prompt:'Label Earth layers from outside to inside.',answer:'Crust -> mantle -> core.'},
{type:'explain',prompt:'What does plate tectonics explain about Earth’s surface?',answer:'Moving plates shape continents, ocean basins, mountains, earthquakes, and volcanoes.'},
{type:'matching',prompt:'Match subduction, accretion, and spreading with: one plate sinks; material is added; plates move apart.',answer:'Subduction: one plate sinks. Accretion: material is added. Spreading: plates move apart.'},
{type:'classification',prompt:'Classify fold, fault, earthquake, and volcano as bend, break with movement, sudden shaking, or magma reaching surface.',answer:'Fold bend; fault break with movement; earthquake sudden shaking; volcano magma reaches surface.'},
{type:'classification',prompt:'A freeze crack in rock and a river carrying sediment: which is weathering and which is erosion?',answer:'Freeze crack is weathering. River carrying sediment is erosion.'},
{type:'sequence',prompt:'Put evaporation, condensation, and precipitation in order and describe each.',answer:'Evaporation liquid to vapor; condensation vapor to droplets/clouds; precipitation water falls.'},
{type:'map-analysis',prompt:'Explain why freshwater is limited even though much of Earth is covered by water.',answer:'Most water is salt water or unavailable; usable freshwater is limited and unevenly distributed.'},
{type:'scenario',prompt:'Volcanic island challenge: identify one internal force, one external force, one hydrosphere example, one lithosphere example, one biosphere example, and one system interaction.',answer:'Volcanism/internal; rain/streams erosion external; rain/streams hydrosphere; mountains lithosphere; plants biosphere; water interacts with rock and plants.'}
]}
function questionLabel(type){return ({definition:'Vocabulary in context',matching:'Match / connect',classification:'Classify',sequence:'Sequence',diagram:'Diagram / model',scenario:'Scenario',source_question:'Text evidence',explain:'Explain',check:'Mastery check','map-analysis':'Map / spatial analysis'}[type]||'Chapter question')}
function worksheetControl(q,i,value){if(q.type==='matching')return `<div class="match-box"><span>Term</span><b>→</b><span>Example / meaning</span></div><textarea oninput="saveAnswer(${i},this.value)" placeholder="Write the match or connection.">${esc(value)}</textarea>`;if(q.type==='map-analysis')return `<div class="mini-visual geo-mini"><span>Location</span><b>→</b><span>Pattern</span><b>→</b><span>Cause</span><b>→</b><span>Decision</span></div><textarea oninput="saveAnswer(${i},this.value)" placeholder="Use place, pattern, and evidence.">${esc(value)}</textarea>`;if(q.type==='scenario')return `<div class="mini-visual bio-mini"><span>Evidence</span><b>→</b><span>Process</span><b>→</b><span>Prediction</span><b>→</b><span>Reason</span></div><textarea oninput="saveAnswer(${i},this.value)" placeholder="Use evidence and explain why.">${esc(value)}</textarea>`;return `<textarea oninput="saveAnswer(${i},this.value)" placeholder="Short answer is enough.">${esc(value)}</textarea>`}
function saveAnswer(i,v){let key=`${S.subject}-${S.chapter}-worksheet`;saved[key]=saved[key]||{};saved[key][i]=v;save()}
function check(ch){let key=`${S.subject}-${ch.number}-check`;let vals=saved[key]||{};let questions=knowledgeItems(ch);return `<div class="card"><h2>Knowledge check</h2><p class="muted">These questions use chapter terms, examples, and applications. Short answers are enough.</p>${questions.map((q,i)=>`<div class="worksheet-item"><div class="eyebrow">${esc(questionLabel(q.type||'check'))}</div><strong>${i+1}. ${injectTerms(q.prompt,ch)}</strong><textarea oninput="saveCheck(${i},this.value)" placeholder="Answer in 1-3 sentences.">${esc(vals[i]||'')}</textarea><button class="secondary no-print" onclick="revealAnswer(this,${JSON.stringify(q.answer)})">Check answer</button><div class="fb"></div></div>`).join('')}</div>`}
function knowledgeItems(ch){let guide=guideFor(ch);if(guide){let last=guide.steps[guide.steps.length-1];return last.questions.map(q=>({type:'check',prompt:q,answer:last.more||'Use the chapter vocabulary accurately and explain the evidence.'}))}let terms=(ch.vocabulary||[]).slice(0,4);let qs=[];if(terms[0]){let i=termInfo(terms[0]);qs.push({type:'definition',prompt:`Explain ${i.term} and give a chapter example.`,answer:`A strong answer explains: ${i.definition} Example: ${i.example}`})}if(terms[1]){let i=termInfo(terms[1]);qs.push({type:'application',prompt:`How does ${i.term} help explain this chapter's main idea?`,answer:`Use ${i.term} accurately and connect it to evidence from ${ch.title}.`})}qs.push({type:S.subject==='biology'?'scenario':'map-analysis',prompt:S.subject==='biology'?`A new example appears in this chapter's topic. What evidence would you look for before making a biological conclusion?`:`A new place appears in this chapter's region or topic. What map or place evidence would you check before explaining the pattern?`,answer:S.subject==='biology'?'Look for observable evidence, identify the relevant process or structure, and explain cause and effect.':'Look for location, region, physical features, human patterns, and human-environment interaction.'});qs.push(...(ch.reviewQuestions||[]).slice(0,3).map(x=>({type:'source_question',prompt:x,answer:'Use the chapter explanation and vocabulary accurately.'})));return qs.slice(0,8)}
function saveCheck(i,v){let key=`${S.subject}-${S.chapter}-check`;saved[key]=saved[key]||{};saved[key][i]=v;save()}
function revealAnswer(btn,a){btn.parentElement.querySelector('.fb').innerHTML=`<div class="feedback"><strong>Use this to check your thinking:</strong> ${esc(a)}</div>`}
function showGlossary(){S.view='glossary';render()}function glossary(){let c=course();let all=[];c.chapters.forEach(ch=>ch.vocabulary.forEach(v=>all.push({...v,ch:ch.number})));Object.keys(TERM_DEFS[S.subject]||{}).forEach(term=>all.push({term,ch:'guide'}));let seen=new Set();all=all.filter(v=>{let k=v.term.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.term.localeCompare(b.term));return `<div class="wrap"><div class="card"><h1>${esc(c.name)} Glossary</h1><input style="width:100%;padding:12px;border:1px solid var(--line);border-radius:10px" placeholder="Search terms" oninput="filterGlossary(this.value)"><div class="alpha-row no-print">${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(l=>`<button class="secondary" onclick="filterGlossary('${l.toLowerCase()}')">${l}</button>`).join('')}</div><div id="glist" class="glossary-grid" style="margin-top:16px">${all.map(v=>{let info=termInfo(v);return `<button class="glossary-item" data-term="${esc(v.term.toLowerCase())}" onclick='globalTerm(${JSON.stringify(v.term)})'><strong>${esc(info.term)}</strong><div class="muted">${v.ch==='guide'?'Chapter guide':'Chapter '+v.ch}</div><div class="muted">${esc(info.definition.slice(0,110))}${info.definition.length>110?'…':''}</div></button>`}).join('')}</div></div></div>`}
function filterGlossary(v){v=v.toLowerCase();document.querySelectorAll('#glist .glossary-item').forEach(x=>x.style.display=x.dataset.term.includes(v)?'block':'none')}
function globalTerm(term){for(let c of Object.values(S.data))for(let ch of c.chapters){let v=ch.vocabulary.find(x=>x.term===term);if(v){let old=S.subject;S.subject=c.id||old;let info=termInfo(v);S.subject=old;document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><h2>${esc(info.term)}</h2><p>${esc(info.definition)}</p><p class="muted">Found in ${esc(c.name)} Chapter ${ch.number}</p><h3>Example</h3><p>${esc(info.example)}</p><h3>Context</h3><p>${esc(info.context)}</p></div></div>`);return}}let info=termInfo({term});document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><h2>${esc(info.term)}</h2><p>${esc(info.definition)}</p><h3>Example</h3><p>${esc(info.example)}</p></div></div>`)}
function semesterView(n){S.view='semester';S.sem=n;navigate()}function semester(){let c=course(),sem=c.semesters[String(S.sem)];return `<div class="wrap"><div class="card"><div class="eyebrow">${esc(c.name)}</div><h1>Semester ${S.sem} review & final</h1><p>Chapters ${sem.chapters.join(', ')}</p><div class="actions"><button class="primary" onclick="exportSemester(false)">Export practice review PDF</button><button class="secondary" onclick="exportSemester(true)">Export final PDF</button></div>${sem.review.slice(0,20).map((q,i)=>`<div class="worksheet-item"><strong>${i+1}. Chapter ${q.chapter}: ${esc(q.prompt)}</strong></div>`).join('')}</div></div>`}
function parentView(){S.view='parent';navigate()}function parentPage(){let rows=[];for(let [id,c] of Object.entries(S.data)){for(let ch of c.chapters){rows.push(`<tr><td>${esc(c.name)}</td><td>${ch.number}</td><td>${esc(ch.title)}</td><td>${ch.vocabulary.length}</td><td>${ch.sections.length}</td><td>${worksheetItems(ch).length}</td><td>${saved[id+'-'+ch.number+'-done']?'✓':'—'}</td></tr>`)}}return `<div class="wrap">${parentProgressTools()}${parentPacing()}${week2Parent()}${curriculumCompleteness()}<div class="card"><h1>Parent curriculum inspector</h1><p class="muted">Source files and completeness are visible here; Liam's normal screens stay clean.</p><table style="width:100%;border-collapse:collapse"><thead><tr><th>Course</th><th>Ch.</th><th>Title</th><th>Terms</th><th>Sections</th><th>Worksheet items</th><th>Done</th></tr></thead><tbody>${rows.join('')}</tbody></table></div></div>`}
function parentProgressTools(){return `<div class="card progress-tools"><div class="eyebrow">Progress safety</div><h1>Liam progress backup</h1><p class="muted">Progress is saved locally on Liam’s computer using a versioned schema. App updates do not clear this record.</p><div class="actions"><button class="primary" onclick="exportProgressBackup()">Export All Liam Progress</button><button class="secondary" onclick="document.getElementById('progress-import').click()">Import Progress Backup</button><button class="secondary" onclick="exportProgressReport()">Print / Export Progress Report</button><input id="progress-import" class="hidden-file" type="file" accept="application/json,.json" onchange="importProgressBackup(this.files&&this.files[0]);this.value=''"></div><p class="muted">Schema v${saved.__schemaVersion||PROGRESS_SCHEMA_VERSION} · Last saved: ${esc(saved.__updatedAt||'not yet saved')}</p></div>`}
function parentPacing(){let bio=pacingSummary('biology'),geo=pacingSummary('geography');if(!bio||!geo)return '';return `<div class="card pacing-panel"><div class="eyebrow">Parent pacing</div><h1>Calendar-based subject pacing</h1><p class="muted">Uses Liam’s 2026-2027 school year, breaks, subject days, Biology mastery rules, and protected semester review/final days. Skipped or no-school days recalculate quietly; they do not create catch-up debt.</p><div class="grid">${pacingCard(bio)}${pacingCard(geo)}</div><h2>Validation</h2><div class="validation-list">${[...bio.validations,...geo.validations].length?[...bio.validations,...geo.validations].map(x=>`<p class="warn">⚠ ${esc(x)}</p>`).join(''):'<p class="ok">✓ No pacing validation issues detected.</p>'}</div></div>`}
function pacingCard(sum){let subject=sum.subject==='biology'?'Biology':'World Geography',ch=sum.current,plan=sum.currentPlan||{},upcoming=sum.plans.filter(p=>p.type==='chapter').slice(0,5),reserved=sum.plans.filter(p=>p.status==='reserved').length,chapterType=sum.subject==='biology'?window.LiamPacing.chapterComplexity(ch,'biology'):'Weekly chapter';return `<section class="pacing-card"><h2>${esc(subject)}</h2><p><strong>Current:</strong> Chapter ${ch.number} — ${esc(ch.title)}</p><p><strong>Status:</strong> ${esc(sum.status)}</p><p><strong>Chapter type:</strong> ${esc(chapterType)}</p><p><strong>Mastery:</strong> ${sum.mastery||0}%</p><p><strong>Semester 1 target:</strong> ${esc(sum.targets[1])}</p><p><strong>Semester 2 target:</strong> ${esc(sum.targets[2])}</p><p><strong>Available subject sessions:</strong> ${sum.subjectDates.length}</p><p><strong>Reserved review/final days:</strong> ${reserved}</p><p><strong>Next action:</strong> ${sum.subject==='biology'&&sum.mastery>0&&sum.mastery<80?'Targeted review before advancing':plan.type==='chapter'?`Continue ${plan.part||'chapter'}`:'Review/final preparation'}</p><details><summary>Upcoming paced days</summary>${upcoming.map(p=>`<p>${esc(p.date)} — Chapter ${p.chapter}: ${esc(p.title)} ${p.part?`(${esc(p.part)})`:''}</p>`).join('')}</details></section>`}
function week2Parent(){return `<div class="card"><div class="eyebrow">Week 2 parent view</div><h1>Separate mastery tracking</h1><div class="grid">${week2ParentCard('biology',2)}${week2ParentCard('geography',2)}</div></div>`}
function week2ParentCard(subject,n){let c=S.data[subject],ch=c.chapters.find(x=>x.number===n),guide=WEEK2_GUIDES[subject][n];return `<section class="inventory-course"><h2>${esc(c.name)} Week 2</h2><p class="muted">Chapter ${n}: ${esc(ch.title)}</p>${guide.mastery.map((m,i)=>{let done=saved[`${subject}-${n}-guide-done-${Math.min(i,guide.steps.length-1)}`];return `<p>${done?'✓':'○'} ${esc(m)}</p>`}).join('')}<p class="muted">Evidence records: ${Object.keys(saved).filter(k=>k.startsWith(`${subject}-${n}-evidence-`)).length}</p></section>`}
function curriculumCompleteness(){let inv=window.__LIAM_CURRICULUM_INVENTORY__;if(!inv)return `<div class="card"><h1>Course Completeness</h1><p class="muted">Inventory has not been generated yet. Run npm run validate-curriculum.</p></div>`;return `<div class="card"><h1>Course Completeness</h1><p class="muted">Tracks source files, processed curriculum data, and chapters actually rendered in the website. Source hashes are stored for safe future updates.</p><div class="grid">${courseInventoryCard(inv.biology)}${courseInventoryCard(inv.geography)}</div><h2>Supplemental files</h2><div class="inventory-list">${inv.supplemental.map(item=>`<article><strong>${esc(item.name)}</strong><span class="${item.status==='SOURCE_FOUND'?'ok':'bad'}">${esc(item.status)}</span><small>${esc(item.file||'')}</small><code>${item.hash?esc(item.hash.slice(0,16))+'...':'no hash'}</code></article>`).join('')}</div></div>`}
function courseInventoryCard(course){return `<section class="inventory-course"><h2>${esc(course.label)}</h2><p>${course.availableSourceChapters} source chapters · ${course.parsed} parsed · ${course.rendered} rendered · ${course.validated} validated · ${course.intentionallyUnavailable||0} unavailable · ${course.unaccounted} unaccounted</p><div class="inventory-list">${course.chapters.map(row=>`<article><strong>Chapter ${row.chapter}: ${esc(row.title)}</strong><span>${row.statuses.map(status=>`<b class="${status==='FAILED'||status==='MISSING'?'bad':status==='UNAVAILABLE'?'warn':'ok'}">${esc(status)}</b>`).join(' ')}</span><small>${esc(row.sourceFile||row.note||'')}</small><code>${row.hash?esc(row.hash.slice(0,16))+'...':'no hash'}</code></article>`).join('')}</div></section>`}
// Byte-safe text PDF generator. Keeps export reliable when chapter text has curly quotes, arrows, or degree symbols.
function pdfClean(value){return String(value??'').normalize('NFKD').replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/\u2192/g,'->').replace(/\u2022/g,'-').replace(/\u00A0/g,' ').replace(/[^\x09\x0A\x0D\x20-\x7E]/g,'')}
function pdfEscape(value){return pdfClean(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function pdfBlob(lines){const W=612,H=792,margin=48,fs=11,lh=15,maxChars=86,encoder=new TextEncoder();let wrapped=[];for(let line of lines){line=pdfClean(line);if(!line){wrapped.push('');continue}while(line.length>maxChars){let cut=line.lastIndexOf(' ',maxChars);if(cut<30)cut=maxChars;wrapped.push(line.slice(0,cut));line=line.slice(cut).trim()}wrapped.push(line)}let pages=[];let per=Math.floor((H-2*margin)/lh);for(let i=0;i<wrapped.length;i+=per)pages.push(wrapped.slice(i,i+per));if(!pages.length)pages=[['']];let objs=[];let add=s=>{objs.push(s);return objs.length};let byteLen=s=>encoder.encode(s).length;let font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let pageIds=[];let contentIds=[];pages.forEach(pg=>{let stream=`BT /F1 ${fs} Tf ${margin} ${H-margin} Td ${lh} TL `;pg.forEach(l=>{stream+=`(${pdfEscape(l)}) Tj T* `});stream+='ET';contentIds.push(add(`<< /Length ${byteLen(stream)} >>\nstream\n${stream}\nendstream`));pageIds.push(add('PLACEHOLDER'))});let pagesId=add('PLACEHOLDER');pageIds.forEach((pid,i)=>objs[pid-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);objs[pagesId-1]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] >>`;let catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let parts=[],offsets=[0],pos=0;let push=s=>{parts.push(s);pos+=byteLen(s)};push('%PDF-1.4\n');objs.forEach((o,i)=>{offsets.push(pos);push(`${i+1} 0 obj\n${o}\nendobj\n`)});let xref=pos;push(`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`);for(let i=1;i<offsets.length;i++)push(String(offsets[i]).padStart(10,'0')+' 00000 n \n');push(`trailer << /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(parts,{type:'application/pdf'})}
function download(blob,name){let url=URL.createObjectURL(blob);let isPdf=blob.type==='application/pdf'||/\.pdf$/i.test(name);let preview=isPdf?window.open(url,'_blank','noopener'):null;let a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();let host=document.querySelector('.card')||document.body;let old=document.getElementById('export-status');if(old)old.remove();let panel=document.createElement('div');panel.id='export-status';panel.className='export-panel';panel.innerHTML=`<strong>${isPdf?'PDF':'File'} ready:</strong> ${esc(name)}<div class="actions"><a class="primary" href="${url}" download="${esc(name)}">Download ${isPdf?'PDF':'File'}</a>${isPdf?`<a class="secondary" href="${url}" target="_blank" rel="noopener">Open PDF</a>`:''}</div>${isPdf?`<iframe title="PDF preview" src="${url}"></iframe>`:''}`;host.prepend(panel);if(isPdf&&!preview)panel.insertAdjacentHTML('beforeend','<p class="muted">If the preview does not appear, use Open PDF or Download PDF.</p>');setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},600000)}
function exportWorksheet(mode){let ch=chap();let key=`${S.subject}-${ch.number}-worksheet`;let vals=saved[key]||{};let lines=[`${course().name} Chapter ${ch.number} ${mode==='key'?'Answer Key':'Worksheet'}`,ch.title,'Student: Liam    Grade: 9    Date: '+new Date().toLocaleDateString(),''];worksheetItems(ch).forEach((q,i)=>{lines.push(`${i+1}. [${questionLabel(q.type)}] ${q.prompt}`);if(mode==='key')lines.push(`Answer guide: ${q.answer}`);else if(mode==='completed'&&vals[i])lines.push(`Liam's answer: ${vals[i]}`);else lines.push('','____________________________________________________________','____________________________________________________________','')});download(pdfBlob(lines),`Liam_${S.subject==='biology'?'Biology':'World_Geography'}_Chapter_${String(ch.number).padStart(2,'0')}_${mode==='key'?'Answer_Key':mode==='completed'?'Completed_Worksheet':'Blank_Worksheet'}.pdf`)}
function exportSemester(finalMode){let c=course(),sem=c.semesters[String(S.sem)],qs=(finalMode?sem.final:sem.review).slice(0,30);let lines=[`${c.name} Semester ${S.sem} ${finalMode?'Final':'Practice Review'}`,'Student: Liam    Grade: 9',''];qs.forEach((q,i)=>{lines.push(`${i+1}. ${q.prompt}`,'','____________________________________________________________','')});download(pdfBlob(lines),`Liam_${S.subject}_Semester_${S.sem}_${finalMode?'Final':'Practice'}.pdf`)}
function backupPayload(){return {student:STUDENT,schemaVersion:PROGRESS_SCHEMA_VERSION,exportedAt:new Date().toISOString(),app:'Liam Learning',progress:saved}}
function exportProgressBackup(){save();let blob=new Blob([JSON.stringify(backupPayload(),null,2)],{type:'application/json'});download(blob,`Liam_DeVries_Learning_Backup_${new Date().toISOString().slice(0,10)}.json`)}
function validateBackupPayload(obj){if(!obj||typeof obj!=='object')return 'Backup is not a JSON object.';let progress=obj.progress||obj;if(!progress||typeof progress!=='object')return 'Backup does not contain a progress object.';if(progress.__schemaVersion&&Number(progress.__schemaVersion)>PROGRESS_SCHEMA_VERSION)return 'Backup uses a newer schema than this app can read.';return ''}
function importProgressBackup(file){if(!file)return;let reader=new FileReader();reader.onload=()=>{try{let obj=JSON.parse(String(reader.result||''));let error=validateBackupPayload(obj);if(error){alert(error);return}let progress=migrateProgress(obj.progress||obj);let keys=Object.keys(progress).filter(k=>!k.startsWith('__')).length;if(!confirm(`Restore this Liam progress backup? It contains ${keys} saved progress entries. A backup of the current record will be created first.`))return;backupRawProgress('manual import restore',localStorage.getItem(PROGRESS_KEY)||'');saved=progress;save();alert('Progress backup restored.');render(false)}catch(e){alert('Could not import backup: '+String(e&&e.message||e))}};reader.readAsText(file)}
function progressReportLines(){let lines=['Liam DeVries Learning Progress Report','Grade: 9','Generated: '+new Date().toLocaleString(),'Schema version: '+(saved.__schemaVersion||PROGRESS_SCHEMA_VERSION),'Last saved: '+(saved.__updatedAt||'not yet saved'),''];for(const [id,c] of Object.entries(S.data)){lines.push(c.name);let current=saved[id+'-current']||c.chapters[0].number;lines.push('Current chapter: '+current);let done=c.chapters.filter(ch=>saved[id+'-'+ch.number+'-done']).map(ch=>ch.number);lines.push('Completed chapters: '+(done.join(', ')||'none yet'));let worksheets=Object.keys(saved).filter(k=>k.startsWith(id+'-')&&k.endsWith('-worksheet')).length;let checks=Object.keys(saved).filter(k=>k.startsWith(id+'-')&&k.endsWith('-check')).length;let evidence=Object.keys(saved).filter(k=>k.startsWith(id+'-')&&k.includes('-evidence-')).length;lines.push('Worksheet attempts: '+worksheets);lines.push('Knowledge-check attempts: '+checks);lines.push('Evidence records: '+evidence);lines.push('')}return lines}
function exportProgressReport(){download(pdfBlob(progressReportLines()),`Liam_DeVries_Progress_Report_${new Date().toISOString().slice(0,10)}.pdf`)}
function render(){try{let body=S.view==='home'?home():S.view==='course'?coursePage():S.view==='chapter'?chapterPage():S.view==='glossary'?glossary():S.view==='semester'?semester():parentPage();document.getElementById('app').innerHTML=appTop()+body}catch(e){document.getElementById('app').innerHTML=`<div class="wrap"><div class="card"><h1>App error</h1><pre>${esc(e&&e.stack?e.stack:e)}</pre><p class="muted">Progress has not been cleared. Export a backup from Parent Mode after this error is fixed.</p></div></div>`}}
function bootReady(){applyRoute();navigate(true);window.addEventListener('popstate',()=>{applyRoute();render(false);window.scrollTo(0,0)});window.addEventListener('hashchange',()=>{applyRoute();render(false)})}
function installAutosave(){let app=document.getElementById('app');if(!app||app.__autosaveInstalled)return;app.__autosaveInstalled=true;app.addEventListener('input',e=>{let t=e.target;if(!t||t.tagName!=='TEXTAREA')return;if(t.dataset.autosaveKey){saved[t.dataset.autosaveKey]=t.value;save();return}if(t.closest('.worksheet-item')&&S.tab==='worksheet'){let all=[...document.querySelectorAll('.worksheet-item textarea')];let i=all.indexOf(t);if(i>=0)saveAnswer(i,t.value);return}if(t.closest('.worksheet-item')&&S.tab==='check'){let all=[...document.querySelectorAll('.worksheet-item textarea')];let i=all.indexOf(t);if(i>=0)saveCheck(i,t.value)}})}
function boot(){installAutosave();if(window.__LIAM_COURSE_DATA__){S.data=window.__LIAM_COURSE_DATA__;bootReady();return}fetch('data/course-data.json').then(r=>r.json()).then(d=>{S.data=d;bootReady()}).catch(e=>document.getElementById('app').innerHTML=`<div class="wrap"><div class="card"><h1>Could not load course data</h1><pre>${esc(e&&e.stack?e.stack:e)}</pre></div></div>`)}
boot();
