
const S={data:null,subject:'biology',chapter:1,view:'home',tab:'learn'};
let saved={};
try{saved=JSON.parse(localStorage.getItem('liam-progress')||'{}')||{}}catch(e){saved={};localStorage.removeItem('liam-progress')}
const TERM_DEFS={
biology:{
biology:['The study of life and living things.','A biologist studies organisms, cells, ecosystems, heredity, evolution, and how living systems work.'],
organism:['A living thing that has all the characteristics of life.','A bacterium, oak tree, mushroom, dog, and human are all organisms.'],
organization:['The orderly structure of living things, from cells to tissues, organs, organ systems, organisms, populations, and ecosystems.','A heart cell, heart tissue, the heart, and the circulatory system show biological organization.'],
reproduction:['The process by which living things produce offspring.','Bacteria dividing and flowering plants making seeds are examples of reproduction.'],
species:['A group of similar organisms that can breed and produce fertile offspring in nature.','Different bird species may live in the same forest but reproduce within their own species.'],
growth:['An increase in living material or body size.','A seedling growing into a mature plant shows growth.'],
development:['The changes an organism goes through during its life.','A tadpole becoming a frog is development.'],
environment:['An organism’s surroundings, including living and nonliving factors.','Temperature, water, food, predators, and shelter are parts of an organism’s environment.'],
stimulus:['A change in an organism’s surroundings that causes a response.','Bright light can be a stimulus that causes pupils to get smaller.'],
response:['A reaction to a stimulus.','A plant bending toward light is a response.'],
homeostasis:['The regulation of stable internal conditions needed for survival.','Sweating helps the body maintain temperature homeostasis.'],
energy:['The ability to cause change or do work.','Cells use energy from food to build molecules, move materials, and grow.'],
adaptation:['An inherited structure, behavior, or process that helps an organism survive and reproduce.','Camouflage can be an adaptation that helps an animal avoid predators.'],
evolution:['Change in inherited traits of populations over generations.','A population becoming better suited to its environment over many generations is evolution.'],
cell:['The basic unit of structure and function in living things.','A single bacterium is one cell; plants and animals are made of many cells.'],
ecology:['The study of interactions among organisms and between organisms and their environments.','Ecology explains how wolves, deer, plants, water, and climate affect one another.'],
ecosystem:['A community of organisms and the nonliving environment they interact with.','A pond ecosystem includes fish, algae, water, sunlight, and minerals.'],
'abiotic factor':['A nonliving part of the environment that affects organisms.','Sunlight, temperature, water, and soil are abiotic factors.'],
'biotic factor':['A living or once-living part of the environment.','Plants, animals, fungi, and bacteria are biotic factors.'],
population:['All members of the same species living in the same area at the same time.','All the deer in one forest make up a deer population.'],
community:['All the populations of different species living and interacting in an area.','Trees, birds, insects, fungi, and mammals in a forest form a community.'],
DNA:['The genetic material that carries instructions for life processes.','DNA contains instructions for traits such as some eye colors or plant characteristics.']
},
geography:{
geography:['The study of Earth’s physical features, living things, places, and how people interact with environments.','Geography explains where things are, why they are there, and how places are connected.'],
location:['The position of a place on Earth.','A school can be described by its street address, coordinates, or nearby landmarks.'],
'absolute location':['The exact position of a place, often described with latitude and longitude.','Dallas is near 32°N, 96°W.'],
'relative location':['Where a place is in relation to other places.','New Orleans is south of Baton Rouge and near the mouth of the Mississippi River.'],
hemisphere:['One half of Earth, such as Northern, Southern, Eastern, or Western Hemisphere.','The Equator divides Earth into Northern and Southern Hemispheres.'],
'grid system':['A network of latitude and longitude lines used to locate places.','A map grid helps identify a city’s exact position.'],
latitude:['Distance north or south of the Equator, measured in degrees.','A place at 30°N is north of the Equator.'],
longitude:['Distance east or west of the Prime Meridian, measured in degrees.','A place at 90°W is west of the Prime Meridian.'],
place:['A location with physical and human characteristics that make it meaningful.','A desert city has climate, landforms, buildings, roads, and cultural features.'],
region:['An area with shared physical or human characteristics.','The Midwest is a region often connected with farming and certain climate patterns.'],
'formal region':['A region defined by a common measurable trait.','A state, country, or climate zone can be a formal region.'],
'functional region':['A region organized around a central point and its connections.','A city and its suburbs can form a functional region.'],
'perceptual region':['A region based on people’s feelings or ideas about a place.','“The South” can be a perceptual region.'],
ecosystem:['A community of living things and the nonliving environment they depend on.','A coral reef ecosystem includes coral, fish, sunlight, water, and minerals.'],
movement:['The flow of people, goods, ideas, or information from place to place.','Trade routes and migration are examples of movement.'],
'human-environment interaction':['The ways people use, adapt to, and change the environment.','Irrigation, farming, roads, and dams are human-environment interactions.'],
'physical geography':['The study of Earth’s natural features and physical systems.','Mountains, rivers, climate, and vegetation are part of physical geography.'],
'human geography':['The study of people, cultures, economies, settlements, and movement across Earth.','Population density and migration are human geography topics.'],
hydrosphere:['All of Earth’s water, including oceans, rivers, lakes, ice, and water vapor.','The Pacific Ocean and polar ice are parts of the hydrosphere.'],
lithosphere:['Earth’s land and rocky outer layer.','Continents, ocean floors, and mountains are part of the lithosphere.'],
atmosphere:['The layer of gases surrounding Earth.','Weather happens in the lower atmosphere.'],
biosphere:['The part of Earth where life exists.','Forests, oceans, grasslands, and soil ecosystems are parts of the biosphere.']
}
};
function save(){localStorage.setItem('liam-progress',JSON.stringify(saved))}
function esc(s){return String(s||'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function course(){return S.data[S.subject]}function chap(){return course().chapters.find(c=>c.number==S.chapter)||course().chapters[0]}
function termInfo(v){let key=String(v.term||v).toLowerCase();let known=TERM_DEFS[S.subject]?.[key]||TERM_DEFS.biology[key]||TERM_DEFS.geography[key];let raw=typeof v==='object'?v.definition:'';let context=typeof v==='object'?v.context:'';let weak=!raw||raw.length<25||/^(and|or|the|a)\b/i.test(raw)||/^\W*$/.test(raw)||/\(p\.|post-|Figure \d/i.test(raw);let definition=known?known[0]:weak?`${v.term||v} is a chapter term Liam should use to explain a specific ${S.subject==='biology'?'living system, process, structure, or relationship':'place, region, pattern, map, or human-environment relationship'}.`:raw;let example=known?known[1]:context&&context!==raw?context:`Use ${v.term||v} in a real chapter example and explain why it matters.`;return {term:typeof v==='object'?v.term:v,definition,example,context:context||example}}
function top(){return `<div class="top"><div class="brand">🎓 Liam Learning</div><button class="navbtn ${S.view==='home'?'active':''}" onclick="goHome()">Home</button><button class="navbtn ${S.subject==='biology'&&S.view!=='home'?'active':''}" onclick="openCourse('biology')">🧪 Biology</button><button class="navbtn ${S.subject==='geography'&&S.view!=='home'?'active':''}" onclick="openCourse('geography')">🌍 World Geography</button><button class="navbtn" onclick="parentView()">Parent</button></div>`}
function goHome(){S.view='home';render()} function openCourse(id){S.subject=id; S.view='course'; const key=id+'-current'; S.chapter=saved[key]||courseById(id).chapters[0].number; render()} function courseById(id){return S.data[id]}
function setChapter(n){S.chapter=n; saved[S.subject+'-current']=n;save();S.view='chapter';S.tab='learn';render();window.scrollTo(0,0)}
function markChapter(){saved[S.subject+'-'+S.chapter+'-done']=true;saved[S.subject+'-current']=S.chapter;save();render()}
function home(){let b=S.data.biology,g=S.data.geography; let bc=saved['biology-current']||b.chapters[0].number,gc=saved['geography-current']||g.chapters[0].number;let bch=b.chapters.find(x=>x.number==bc),gch=g.chapters.find(x=>x.number==gc);return `<div class="wrap"><div class="today"><div class="eyebrow" style="color:#9dd8c8">One subject at a time</div><div class="h1">Today can stay small.</div><p class="muted">Choose one course. Learn in short blocks. Stop when the learning is done.</p></div><div class="grid"><div class="card subject bio"><h2>🧪 Biology</h2><p>Current: Chapter ${bch.number} — ${esc(bch.title)}</p><p class="muted">${b.chapters.length} available chapters · Chapter 16 was unavailable in the supplied materials.</p><button class="primary" onclick="openCourse('biology')">Continue Biology</button></div><div class="card subject geo"><h2>🌍 World Geography</h2><p>Current: Chapter ${gch.number} — ${esc(gch.title)}</p><p class="muted">${g.chapters.length} chapters · complete Chapter 1–34 set.</p><button class="primary" onclick="openCourse('geography')">Continue Geography</button></div></div></div>`}
function coursePage(){let c=course();let curr=saved[S.subject+'-current']||c.chapters[0].number;let sem1=c.chapters.filter(x=>x.semester===1),sem2=c.chapters.filter(x=>x.semester===2);return `<div class="wrap"><div class="hero"><div><div class="eyebrow">${esc(c.name)}</div><div class="h1">Course map</div><p class="muted">Every supplied chapter is visible here. Future chapters are viewable; progress is tracked separately for each course.</p><div class="actions"><button class="primary" onclick="setChapter(${curr})">Continue Chapter ${curr}</button><button class="secondary" onclick="showGlossary()">Glossary</button><button class="secondary" onclick="semesterView(1)">Semester 1 review</button><button class="secondary" onclick="semesterView(2)">Semester 2 review</button></div></div><div><img src="${c.chapters[0].cover}" alt="course textbook"></div></div>${chapterGroup('Semester 1',sem1,curr)}${chapterGroup('Semester 2',sem2,curr)}${c.missing?.length?`<div class="card" style="margin-top:18px"><strong>Source note:</strong> Chapter ${c.missing.join(', ')} was not available in the supplied Biology materials and has not been fabricated.</div>`:''}</div>`}
function chapterGroup(title,arr,curr){return `<div class="card" style="margin-top:18px"><div class="course-head"><h2>${title}</h2><span class="muted">${arr.length} chapters</span></div><div class="chapter-list">${arr.map(ch=>`<button class="chapter-link ${ch.number==curr?'current':''}" onclick="setChapter(${ch.number})"><strong>Chapter ${ch.number}</strong><small>${esc(ch.title)}</small><small>${ch.sections.length} sections · ${ch.vocabulary.length} words · ${ch.worksheet.length} worksheet items</small>${saved[S.subject+'-'+ch.number+'-done']?'<small>✓ completed</small>':'<small>Open / upcoming</small>'}</button>`).join('')}</div></div>`}
function injectTerms(text,ch){let out=esc(text);let terms=[...(ch.vocabulary||[])].sort((a,b)=>String(b.term).length-String(a.term).length);for(const v of terms){let t=String(v.term||'').trim();if(!t||t.length<3)continue;let safe=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');let re=new RegExp(`(^|[^A-Za-z0-9])(${safe})(?=$|[^A-Za-z0-9])`,'gi');out=out.replace(re,(m,p1,p2)=>`${p1}<button class="term" onclick='event.stopPropagation();termModal(${JSON.stringify(v.term)})'>${p2}</button>`)}return out}
function chapterPage(){let ch=chap(),c=course();let idx=c.chapters.findIndex(x=>x.number===ch.number);let prev=c.chapters[idx-1],next=c.chapters[idx+1];let pct=saved[S.subject+'-'+ch.number+'-done']?100:Math.min(85, Math.round((saved[S.subject+'-'+ch.number+'-progress']||0)*100));return `<div class="wrap"><div class="hero"><div><div class="eyebrow">${esc(c.name)} · Chapter ${ch.number}</div><div class="h1">${esc(ch.title)}</div><p class="muted">Learn here. The original PDF is reference material, not required reading.</p><div class="chapter-jump no-print"><label>Jump to chapter <select onchange="setChapter(Number(this.value))">${c.chapters.map(x=>`<option value="${x.number}" ${x.number===ch.number?'selected':''}>${x.number}. ${esc(x.title)}</option>`).join('')}</select></label><button class="secondary" onclick="openCourse('${S.subject}')">Browse all chapters</button></div><div class="progress"><span style="width:${pct}%"></span></div></div><img src="${ch.cover}" alt="chapter image"></div><div class="tabs no-print"><button class="tab ${S.tab==='learn'?'active':''}" onclick="tab('learn')">Learn</button><button class="tab ${S.tab==='words'?'active':''}" onclick="tab('words')">Important words</button><button class="tab ${S.tab==='notes'?'active':''}" onclick="tab('notes')">Study guide</button><button class="tab ${S.tab==='worksheet'?'active':''}" onclick="tab('worksheet')">Worksheet</button><button class="tab ${S.tab==='check'?'active':''}" onclick="tab('check')">Knowledge check</button></div><div id="tabcontent">${tabContent(ch)}</div><div class="bottom-nav no-print"><button class="secondary" ${!prev?'disabled':''} onclick="${prev?`setChapter(${prev.number})`:''}">← ${prev?'Chapter '+prev.number:'Start'}</button><button class="primary" onclick="markChapter()">${saved[S.subject+'-'+ch.number+'-done']?'✓ Chapter complete':'Mark chapter complete'}</button><button class="secondary" ${!next?'disabled':''} onclick="${next?`setChapter(${next.number})`:''}">${next?'Chapter '+next.number:'End'} →</button></div></div>`}
function tab(t){S.tab=t;render()}
function tabContent(ch){if(S.tab==='words')return words(ch);if(S.tab==='notes')return notes(ch);if(S.tab==='worksheet')return worksheet(ch);if(S.tab==='check')return check(ch);return learn(ch)}
function learn(ch){let objectives=ch.objectives?.length?`<div class="card"><h2>What you'll learn</h2>${ch.objectives.map(x=>`<p>• ${injectTerms(x,ch)}</p>`).join('')}</div>`:'';let places=ch.places?.length?`<div class="card"><h3>Places to know</h3>${ch.places.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>`:'';return `${objectives}${places}<div class="card" style="margin-top:18px"><h2>Chapter lesson</h2><p class="muted">Short blocks, definitions when you need them, and quick checks between ideas.</p>${ch.sections.map((s,si)=>`<div class="lesson-block"><div class="eyebrow">Section ${esc(s.number)}</div><h2>${injectTerms(s.title,ch)}</h2>${s.blocks.map((b,bi)=>`<p>${injectTerms(b,ch)}</p>${bi===0?conceptActivity(ch,si):''}`).join('')}${si===0?`<img class="visual" src="${ch.visual}" alt="textbook-derived visual reference">`:''}</div>`).join('')}</div>`}
function conceptActivity(ch,si){let v=ch.vocabulary[si%Math.max(1,ch.vocabulary.length)];if(!v)return '';let info=termInfo(v);let subject=S.subject;let title=subject==='biology'?'Science quick activity':'Map thinking quick activity';let prompt=subject==='biology'?`Use ${info.term} to make a prediction or explain cause and effect.`:`Use ${info.term} to explain a place, region, movement, or human-environment decision.`;let choices=subject==='biology'?[`Connect ${info.term} to evidence from the living system.`,`Memorize ${info.term} without an example.`,`Ignore what happens in the organism or process.`]:[`Connect ${info.term} to a map, place, or spatial pattern.`,`Describe the place without location clues.`,`Ignore physical and human geography.`];return `<div class="interaction"><strong>${title}</strong><p>${esc(prompt)}</p><div class="choice-row">${choices.map((choice,i)=>`<button class="secondary" onclick="showActivityFeedback(this,${i===0},${JSON.stringify(info.term)},${JSON.stringify(info.definition)},${JSON.stringify(info.example)})">${esc(choice)}</button>`).join('')}</div><div class="mini-visual ${subject==='biology'?'bio-mini':'geo-mini'}">${miniVisual(ch,info)}</div><div class="fb"></div></div>`}
function miniVisual(ch,info){if(S.subject==='biology')return `<span>Observe</span><b>→</b><span>${esc(info.term)}</span><b>→</b><span>Predict</span><b>→</b><span>Explain with evidence</span>`;return `<span>Where?</span><b>→</b><span>${esc(info.term)}</span><b>→</b><span>Pattern</span><b>→</b><span>Why there?</span>`}
function showActivityFeedback(btn,ok,term,def,example){btn.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('picked'));btn.classList.add('picked');btn.closest('.interaction').querySelector('.fb').innerHTML=ok?`<div class="feedback"><strong>${esc(term)}</strong>: ${esc(def)}<br>${esc(example)}</div>`:`<div class="feedback warn"><strong>Try again.</strong> A good answer connects the term to evidence and a real example.</div>`}
function words(ch){return `<div class="card"><h2>Important words</h2><p class="muted">Click any word to see what it means, context, and an example from the chapter.</p><div class="glossary-grid">${ch.vocabulary.map(v=>{let info=termInfo(v);return `<button class="glossary-item" onclick='termModal(${JSON.stringify(v.term)})'><strong>${esc(info.term)}</strong><div class="muted" style="margin-top:6px">${esc(info.definition.slice(0,150))}${info.definition.length>150?'…':''}</div></button>`}).join('')}</div></div>`}
function termModal(term){let v=chap().vocabulary.find(x=>x.term===term) || Object.values(S.data).flatMap(c=>c.chapters).flatMap(c=>c.vocabulary).find(x=>x.term===term);if(!v)return;let info=termInfo(v);document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><div class="eyebrow">Important word</div><h2>${esc(info.term)}</h2><h3>What it means</h3><p>${esc(info.definition)}</p><h3>Example</h3><p>${esc(info.example)}</p><h3>In the chapter</h3><p>${esc(info.context)}</p><div class="interaction"><strong>Check yourself</strong><p>Can you explain this term in your own words and give one example?</p></div></div></div>`)}
function notes(ch){return `<div class="grid"><div class="card"><h2>Study guide</h2><h3>Big ideas</h3>${ch.objectives.map(x=>`<p>• ${injectTerms(x,ch)}</p>`).join('')}<h3>Important words</h3>${ch.vocabulary.slice(0,12).map(x=>`<button class="term" onclick='termModal(${JSON.stringify(x.term)})'>${esc(x.term)}</button> `).join('')}<h3>Know this</h3>${ch.vocabulary.slice(0,6).map(v=>{let i=termInfo(v);return `<p>• <strong>${esc(i.term)}</strong>: ${esc(i.definition)}</p>`}).join('')}<h3>Be able to explain</h3>${ch.sections.map(s=>`<p>• ${injectTerms(s.title,ch)}</p>`).join('')}<h3>Be able to apply</h3><p>${S.subject==='biology'?'Use evidence to classify, predict, sequence, or explain a biological process.':'Use map evidence to explain location, region, climate, population, movement, or human-environment interaction.'}</p></div><div class="card"><h2>Chapter notes</h2>${ch.sections.map(s=>`<h3>${injectTerms(s.title,ch)}</h3><p>${injectTerms((s.blocks||[]).slice(0,2).join(' '),ch)}</p>`).join('')}</div></div>`}
function worksheet(ch){let key=`${S.subject}-${ch.number}-worksheet`;let vals=saved[key]||{};return `<div class="card"><div class="actions no-print"><button class="primary" onclick="exportWorksheet('blank')">Export blank PDF</button><button class="primary" onclick="exportWorksheet('completed')">Export completed PDF</button><button class="secondary" onclick="window.print()">Print / Save PDF</button><button class="secondary" onclick="exportWorksheet('key')">Parent answer key PDF</button></div><h1>${esc(course().name)} Chapter ${ch.number} Worksheet</h1><p>Student: Liam &nbsp;&nbsp; Grade: 9 &nbsp;&nbsp; Date: ${new Date().toLocaleDateString()}</p>${worksheetItems(ch).map((q,i)=>`<div class="worksheet-item ${esc(q.type)}"><div class="eyebrow">${esc(questionLabel(q.type))}</div><strong>${i+1}. ${injectTerms(q.prompt,ch)}</strong>${worksheetControl(q,i,vals[i]||'')}</div>`).join('')}</div>`}
function worksheetItems(ch){let base=(ch.worksheet||[]).slice(0,10);let terms=(ch.vocabulary||[]).slice(0,4).map((v,i)=>({type:i%2?'matching':'definition',prompt:`${i%2?'Match or connect':'Define'} ${v.term} using a chapter example.`,answer:termInfo(v).definition}));let scenario={type:S.subject==='biology'?'scenario':'map-analysis',prompt:S.subject==='biology'?`Use evidence from ${ch.title} to make a prediction about a living system, process, or experiment.`:`Use evidence from ${ch.title} to explain a place, region, climate, population pattern, or human-environment decision.`,answer:'Answer should use accurate chapter vocabulary and explain the reasoning with evidence.'};let varied=[...terms,scenario,...base].slice(0,14);return varied}
function questionLabel(type){return ({definition:'Vocabulary in context',matching:'Match / connect',scenario:'Science scenario',source_question:'Text evidence',explain:'Explain', 'map-analysis':'Map / spatial analysis'}[type]||'Chapter question')}
function worksheetControl(q,i,value){if(q.type==='matching')return `<div class="match-box"><span>Term</span><b>→</b><span>Example / meaning</span></div><textarea oninput="saveAnswer(${i},this.value)" placeholder="Write the match or connection.">${esc(value)}</textarea>`;if(q.type==='map-analysis')return `<div class="mini-visual geo-mini"><span>Location</span><b>→</b><span>Pattern</span><b>→</b><span>Cause</span><b>→</b><span>Decision</span></div><textarea oninput="saveAnswer(${i},this.value)" placeholder="Use place, pattern, and evidence.">${esc(value)}</textarea>`;if(q.type==='scenario')return `<div class="mini-visual bio-mini"><span>Evidence</span><b>→</b><span>Process</span><b>→</b><span>Prediction</span><b>→</b><span>Reason</span></div><textarea oninput="saveAnswer(${i},this.value)" placeholder="Use evidence and explain why.">${esc(value)}</textarea>`;return `<textarea oninput="saveAnswer(${i},this.value)" placeholder="Short answer is enough.">${esc(value)}</textarea>`}
function saveAnswer(i,v){let key=`${S.subject}-${S.chapter}-worksheet`;saved[key]=saved[key]||{};saved[key][i]=v;save()}
function check(ch){let key=`${S.subject}-${ch.number}-check`;let vals=saved[key]||{};let questions=knowledgeItems(ch);return `<div class="card"><h2>Knowledge check</h2><p class="muted">These questions use chapter terms, examples, and applications. Short answers are enough.</p>${questions.map((q,i)=>`<div class="worksheet-item"><div class="eyebrow">${esc(questionLabel(q.type||'check'))}</div><strong>${i+1}. ${injectTerms(q.prompt,ch)}</strong><textarea oninput="saveCheck(${i},this.value)" placeholder="Answer in 1-3 sentences.">${esc(vals[i]||'')}</textarea><button class="secondary no-print" onclick="revealAnswer(this,${JSON.stringify(q.answer)})">Check answer</button><div class="fb"></div></div>`).join('')}</div>`}
function knowledgeItems(ch){let terms=(ch.vocabulary||[]).slice(0,4);let qs=[];if(terms[0]){let i=termInfo(terms[0]);qs.push({type:'definition',prompt:`Explain ${i.term} and give a chapter example.`,answer:`A strong answer explains: ${i.definition} Example: ${i.example}`})}if(terms[1]){let i=termInfo(terms[1]);qs.push({type:'application',prompt:`How does ${i.term} help explain this chapter's main idea?`,answer:`Use ${i.term} accurately and connect it to evidence from ${ch.title}.`})}qs.push({type:S.subject==='biology'?'scenario':'map-analysis',prompt:S.subject==='biology'?`A new example appears in this chapter's topic. What evidence would you look for before making a biological conclusion?`:`A new place appears in this chapter's region or topic. What map or place evidence would you check before explaining the pattern?`,answer:S.subject==='biology'?'Look for observable evidence, identify the relevant process or structure, and explain cause and effect.':'Look for location, region, physical features, human patterns, and human-environment interaction.'});qs.push(...(ch.reviewQuestions||[]).slice(0,3).map(x=>({type:'source_question',prompt:x,answer:'Use the chapter explanation and vocabulary accurately.'})));return qs.slice(0,8)}
function saveCheck(i,v){let key=`${S.subject}-${S.chapter}-check`;saved[key]=saved[key]||{};saved[key][i]=v;save()}
function revealAnswer(btn,a){btn.parentElement.querySelector('.fb').innerHTML=`<div class="feedback"><strong>Use this to check your thinking:</strong> ${esc(a)}</div>`}
function showGlossary(){S.view='glossary';render()}function glossary(){let c=course();let all=[];c.chapters.forEach(ch=>ch.vocabulary.forEach(v=>all.push({...v,ch:ch.number})));let seen=new Set();all=all.filter(v=>{let k=v.term.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.term.localeCompare(b.term));return `<div class="wrap"><div class="card"><h1>${esc(c.name)} Glossary</h1><input style="width:100%;padding:12px;border:1px solid var(--line);border-radius:10px" placeholder="Search terms" oninput="filterGlossary(this.value)"><div class="alpha-row no-print">${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(l=>`<button class="secondary" onclick="filterGlossary('${l.toLowerCase()}')">${l}</button>`).join('')}</div><div id="glist" class="glossary-grid" style="margin-top:16px">${all.map(v=>{let info=termInfo(v);return `<button class="glossary-item" data-term="${esc(v.term.toLowerCase())}" onclick='globalTerm(${JSON.stringify(v.term)})'><strong>${esc(info.term)}</strong><div class="muted">Chapter ${v.ch}</div><div class="muted">${esc(info.definition.slice(0,110))}${info.definition.length>110?'…':''}</div></button>`}).join('')}</div></div></div>`}
function filterGlossary(v){v=v.toLowerCase();document.querySelectorAll('#glist .glossary-item').forEach(x=>x.style.display=x.dataset.term.includes(v)?'block':'none')}
function globalTerm(term){for(let c of Object.values(S.data))for(let ch of c.chapters){let v=ch.vocabulary.find(x=>x.term===term);if(v){let old=S.subject;S.subject=c.id||old;let info=termInfo(v);S.subject=old;document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal"><button class="close" onclick="document.getElementById('modal').remove()">✕</button><h2>${esc(info.term)}</h2><p>${esc(info.definition)}</p><p class="muted">Found in ${esc(c.name)} Chapter ${ch.number}</p><h3>Example</h3><p>${esc(info.example)}</p><h3>Context</h3><p>${esc(info.context)}</p></div></div>`);return}}}
function semesterView(n){S.view='semester';S.sem=n;render()}function semester(){let c=course(),sem=c.semesters[String(S.sem)];return `<div class="wrap"><div class="card"><div class="eyebrow">${esc(c.name)}</div><h1>Semester ${S.sem} review & final</h1><p>Chapters ${sem.chapters.join(', ')}</p><div class="actions"><button class="primary" onclick="exportSemester(false)">Export practice review PDF</button><button class="secondary" onclick="exportSemester(true)">Export final PDF</button></div>${sem.review.slice(0,20).map((q,i)=>`<div class="worksheet-item"><strong>${i+1}. Chapter ${q.chapter}: ${esc(q.prompt)}</strong></div>`).join('')}</div></div>`}
function parentView(){S.view='parent';render()}function parent(){let rows=[];for(let [id,c] of Object.entries(S.data)){for(let ch of c.chapters){rows.push(`<tr><td>${esc(c.name)}</td><td>${ch.number}</td><td>${esc(ch.title)}</td><td>${ch.vocabulary.length}</td><td>${ch.sections.length}</td><td>${ch.worksheet.length}</td><td>${saved[id+'-'+ch.number+'-done']?'✓':'—'}</td></tr>`)}}return `<div class="wrap">${curriculumCompleteness()}<div class="card"><h1>Parent curriculum inspector</h1><p class="muted">Source files and completeness are visible here; Liam's normal screens stay clean.</p><table style="width:100%;border-collapse:collapse"><thead><tr><th>Course</th><th>Ch.</th><th>Title</th><th>Terms</th><th>Sections</th><th>Worksheet items</th><th>Done</th></tr></thead><tbody>${rows.join('')}</tbody></table></div></div>`}
function curriculumCompleteness(){let inv=window.__LIAM_CURRICULUM_INVENTORY__;if(!inv)return `<div class="card"><h1>Course Completeness</h1><p class="muted">Inventory has not been generated yet. Run npm run validate-curriculum.</p></div>`;return `<div class="card"><h1>Course Completeness</h1><p class="muted">Tracks source files, processed curriculum data, and chapters actually rendered in the website. Source hashes are stored for safe future updates.</p><div class="grid">${courseInventoryCard(inv.biology)}${courseInventoryCard(inv.geography)}</div><h2>Supplemental files</h2><div class="inventory-list">${inv.supplemental.map(item=>`<article><strong>${esc(item.name)}</strong><span class="${item.status==='SOURCE_FOUND'?'ok':'bad'}">${esc(item.status)}</span><small>${esc(item.file||'')}</small><code>${item.hash?esc(item.hash.slice(0,16))+'...':'no hash'}</code></article>`).join('')}</div></div>`}
function courseInventoryCard(course){return `<section class="inventory-course"><h2>${esc(course.label)}</h2><p>${course.availableSourceChapters} source chapters · ${course.parsed} parsed · ${course.rendered} rendered · ${course.validated} validated · ${course.intentionallyUnavailable||0} unavailable · ${course.unaccounted} unaccounted</p><div class="inventory-list">${course.chapters.map(row=>`<article><strong>Chapter ${row.chapter}: ${esc(row.title)}</strong><span>${row.statuses.map(status=>`<b class="${status==='FAILED'||status==='MISSING'?'bad':status==='UNAVAILABLE'?'warn':'ok'}">${esc(status)}</b>`).join(' ')}</span><small>${esc(row.sourceFile||row.note||'')}</small><code>${row.hash?esc(row.hash.slice(0,16))+'...':'no hash'}</code></article>`).join('')}</div></section>`}
// Minimal standards-compliant text PDF generator
function pdfBlob(lines){const W=612,H=792,margin=48,fs=11,lh=15,maxChars=86;let wrapped=[];for(let line of lines){line=String(line??'');if(!line){wrapped.push('');continue}while(line.length>maxChars){let cut=line.lastIndexOf(' ',maxChars);if(cut<30)cut=maxChars;wrapped.push(line.slice(0,cut));line=line.slice(cut).trim()}wrapped.push(line)}let pages=[];let per=Math.floor((H-2*margin)/lh);for(let i=0;i<wrapped.length;i+=per)pages.push(wrapped.slice(i,i+per));let objs=[];let add=s=>{objs.push(s);return objs.length};let font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let pageIds=[];let contentIds=[];pages.forEach(pg=>{let y=H-margin;let stream=`BT /F1 ${fs} Tf ${margin} ${y} Td `;let first=true;for(let l of pg){let safe=l.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');if(!first)stream+=`0 -${lh} Td `;stream+=`(${safe}) Tj `;first=false}stream+='ET';contentIds.push(add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`));pageIds.push(add('PLACEHOLDER'))});let pagesId=add('PLACEHOLDER');pageIds.forEach((pid,i)=>objs[pid-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);objs[pagesId-1]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] >>`;let catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let out='%PDF-1.4\n';let offs=[0];objs.forEach((o,i)=>{offs.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`});let xref=out.length;out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offs.length;i++)out+=String(offs[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer << /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([out],{type:'application/pdf'})}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function exportWorksheet(mode){let ch=chap();let key=`${S.subject}-${ch.number}-worksheet`;let vals=saved[key]||{};let lines=[`${course().name} Chapter ${ch.number} ${mode==='key'?'Answer Key':'Worksheet'}`,ch.title,'Student: Liam    Grade: 9    Date: '+new Date().toLocaleDateString(),''];worksheetItems(ch).forEach((q,i)=>{lines.push(`${i+1}. [${questionLabel(q.type)}] ${q.prompt}`);if(mode==='key')lines.push(`Answer guide: ${q.answer}`);else if(mode==='completed'&&vals[i])lines.push(`Liam's answer: ${vals[i]}`);else lines.push('','____________________________________________________________','____________________________________________________________','')});download(pdfBlob(lines),`Liam_${S.subject==='biology'?'Biology':'World_Geography'}_Chapter_${String(ch.number).padStart(2,'0')}_${mode==='key'?'Answer_Key':mode==='completed'?'Completed_Worksheet':'Blank_Worksheet'}.pdf`)}
function exportSemester(finalMode){let c=course(),sem=c.semesters[String(S.sem)],qs=(finalMode?sem.final:sem.review).slice(0,30);let lines=[`${c.name} Semester ${S.sem} ${finalMode?'Final':'Practice Review'}`,'Student: Liam    Grade: 9',''];qs.forEach((q,i)=>{lines.push(`${i+1}. ${q.prompt}`,'','____________________________________________________________','')});download(pdfBlob(lines),`Liam_${S.subject}_Semester_${S.sem}_${finalMode?'Final':'Practice'}.pdf`)}
function render(){try{let body=S.view==='home'?home():S.view==='course'?coursePage():S.view==='chapter'?chapterPage():S.view==='glossary'?glossary():S.view==='semester'?semester():parent();document.getElementById('app').innerHTML=top()+body}catch(e){document.getElementById('app').innerHTML=`<div class="wrap"><div class="card"><h1>App error</h1><pre>${esc(e&&e.stack?e.stack:e)}</pre><button class="primary" onclick="localStorage.removeItem('liam-progress');location.reload()">Reset saved progress</button></div></div>`}}
function boot(){if(window.__LIAM_COURSE_DATA__){S.data=window.__LIAM_COURSE_DATA__;render();return}fetch('data/course-data.json').then(r=>r.json()).then(d=>{S.data=d;render()}).catch(e=>document.getElementById('app').innerHTML=`<div class="wrap"><div class="card"><h1>Could not load course data</h1><pre>${esc(e&&e.stack?e.stack:e)}</pre></div></div>`)}
boot();
