(function(){
  function esc(value){return String(value||'').replace(/[&<>"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
  function pdfClean(value){return String(value||'').normalize('NFKD').replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/\u2192/g,'->').replace(/\u2022/g,'-').replace(/\u00A0/g,' ').replace(/[^\x09\x0A\x0D\x20-\x7E]/g,'')}
  function pdfEscape(value){return pdfClean(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
  function pdfBlob(lines){
    var encoder=new TextEncoder(), wrapped=[]; function byteLen(s){return encoder.encode(s).length}
    lines.forEach(function(line){line=pdfClean(line); if(!line){wrapped.push(''); return} while(line.length>86){var cut=line.lastIndexOf(' ',86); if(cut<30)cut=86; wrapped.push(line.slice(0,cut)); line=line.slice(cut).trim()} wrapped.push(line)});
    var pages=[]; for(var i=0;i<wrapped.length;i+=48)pages.push(wrapped.slice(i,i+48)); if(!pages.length)pages=[['']];
    var objs=[]; function add(s){objs.push(s); return objs.length}
    var font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'), pageIds=[], contentIds=[];
    pages.forEach(function(pg){var stream='BT /F1 11 Tf 48 744 Td 15 TL '; pg.forEach(function(l){stream+='('+pdfEscape(l)+') Tj T* '}); stream+='ET'; contentIds.push(add('<< /Length '+byteLen(stream)+' >>\nstream\n'+stream+'\nendstream')); pageIds.push(add('PLACEHOLDER'))});
    var pagesId=add('PLACEHOLDER'); pageIds.forEach(function(pid,i){objs[pid-1]='<< /Type /Page /Parent '+pagesId+' 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 '+font+' 0 R >> >> /Contents '+contentIds[i]+' 0 R >>'}); objs[pagesId-1]='<< /Type /Pages /Count '+pageIds.length+' /Kids ['+pageIds.map(function(x){return x+' 0 R'}).join(' ')+'] >>';
    var catalog=add('<< /Type /Catalog /Pages '+pagesId+' 0 R >>'), parts=[], offs=[0], pos=0; function push(s){parts.push(s); pos+=byteLen(s)}
    push('%PDF-1.4\n'); objs.forEach(function(o,i){offs.push(pos); push((i+1)+' 0 obj\n'+o+'\nendobj\n')}); var xref=pos; push('xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n'); for(var j=1;j<offs.length;j++)push(String(offs[j]).padStart(10,'0')+' 00000 n \n'); push('trailer << /Size '+(objs.length+1)+' /Root '+catalog+' 0 R >>\nstartxref\n'+xref+'\n%%EOF'); return new Blob(parts,{type:'application/pdf'});
  }
  function download(blob,name){var url=URL.createObjectURL(blob); var preview=window.open(url,'_blank','noopener'); var a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); var host=document.querySelector('.card')||document.body, old=document.getElementById('export-status'); if(old)old.remove(); var panel=document.createElement('div'); panel.id='export-status'; panel.className='export-panel'; panel.innerHTML='<strong>PDF ready:</strong> '+esc(name)+'<div class="actions"><a class="primary" href="'+url+'" download="'+esc(name)+'">Download PDF</a><a class="secondary" href="'+url+'" target="_blank" rel="noopener">Open PDF</a></div><iframe title="PDF preview" src="'+url+'"></iframe>'; host.prepend(panel); if(!preview)panel.insertAdjacentHTML('beforeend','<p class="muted">If the preview does not appear, use Open PDF or Download PDF.</p>'); setTimeout(function(){URL.revokeObjectURL(url); a.remove()},600000)}
  function bootFallback(){
    var app=document.getElementById('app');
    if(!app || !/Loading Liam Learning/.test(app.textContent||''))return;
    var data=window.__LIAM_COURSE_DATA__;
    if(!data){app.innerHTML='<div class="wrap"><div class="card"><h1>Course data did not load</h1></div></div>'; return}
    var state={subject:'biology', view:'home', chapter:1, tab:'learn'}, saved={};
    try{saved=JSON.parse(localStorage.getItem('liam-progress')||'{}')||{}}catch(e){saved={}}
    function save(){localStorage.setItem('liam-progress',JSON.stringify(saved))}
    function route(){if(state.view==='home')return '#home'; if(state.view==='course')return '#course/'+state.subject; if(state.view==='chapter')return '#chapter/'+state.subject+'/'+state.chapter+'/'+state.tab; if(state.view==='parent')return '#parent'; return '#home'}
    function applyRoute(){var p=(location.hash||'#home').replace(/^#/,'').split('/').filter(Boolean); if(p[0]==='course'&&data[p[1]]){state.view='course'; state.subject=p[1]; state.chapter=course().chapters[0].number; return} if(p[0]==='chapter'&&data[p[1]]){state.view='chapter'; state.subject=p[1]; state.chapter=Number(p[2])||course().chapters[0].number; state.tab=p[3]||'learn'; return} if(p[0]==='parent'){state.view='parent'; return} state.view='home'}
    function nav(replace){var r=route(); if(location.hash!==r)history[replace?'replaceState':'pushState']({view:state.view,subject:state.subject,chapter:state.chapter,tab:state.tab},'',r); render()}
    function course(){return data[state.subject]}
    function chapter(){return course().chapters.find(function(c){return c.number==state.chapter})||course().chapters[0]}
    function top(){return '<div class="top"><div class="brand">Liam Learning</div><button class="navbtn" data-go="home">Home</button><button class="navbtn" data-subject="biology">Biology</button><button class="navbtn" data-subject="geography">World Geography</button><button class="navbtn" data-go="parent">Parent</button></div>'}
    function home(){return '<div class="wrap"><div class="today"><div class="eyebrow" style="color:#9dd8c8">One subject at a time</div><div class="h1">Today can stay small.</div><p class="muted">Choose one course. Learn in short blocks. Stop when the learning is done.</p></div><div class="grid"><div class="card subject bio"><h2>Biology</h2><p>'+data.biology.chapters.length+' chapters available. Chapter 16 is unavailable.</p><button class="primary" data-subject="biology">Open Biology</button></div><div class="card subject geo"><h2>World Geography</h2><p>'+data.geography.chapters.length+' chapters available.</p><button class="primary" data-subject="geography">Open World Geography</button></div></div><div class="card"><div class="eyebrow">Week 2</div><h2>Ready subject days</h2><div class="grid"><div class="card subject bio"><h3>Biology</h3><p><strong>Chapter 2: Principles of Ecology</strong></p><p class="muted">'+guideStatus("biology")+'</p><button class="primary" data-week2="biology">Continue Biology Week 2</button></div><div class="card subject geo"><h3>World Geography</h3><p><strong>Chapter 2: The Earth</strong></p><p class="muted">'+guideStatus("geography")+'</p><button class="primary" data-week2="geography">Continue Geography Week 2</button></div></div></div></div>'}
    function guideStatus(subject){var g=guide(subject),done=g.steps.filter(function(_,i){return saved[subject+'-2-guide-done-'+i]}).length;return (done?'In progress':'Ready')+' - '+done+'/'+g.steps.length+' blocks complete'}
    function coursePage(){var c=course(); return '<div class="wrap"><div class="hero"><div><div class="eyebrow">'+esc(c.name)+'</div><div class="h1">Course map</div><p class="muted">Every supplied chapter is visible and openable.</p></div><img src="'+esc(c.chapters[0].cover)+'"></div><div class="card" style="margin-top:18px"><div class="chapter-list">'+c.chapters.map(function(ch){return '<button class="chapter-link" data-chapter="'+ch.number+'"><strong>Chapter '+ch.number+'</strong><small>'+esc(ch.title)+'</small><small>'+ch.sections.length+' sections - '+ch.vocabulary.length+' words - '+ch.worksheet.length+' worksheet items</small></button>'}).join('')+'</div></div></div>'}
    function termButton(term){return '<button class="term" data-term="'+esc(term)+'">'+esc(term)+'</button>'}
    function chapterPage(){var ch=chapter(), c=course(); return '<div class="wrap"><div class="hero"><div><div class="eyebrow">'+esc(c.name)+' - Chapter '+ch.number+'</div><div class="h1">'+esc(ch.title)+'</div><p class="muted">Learn here. The PDF is reference material only.</p><div class="chapter-jump"><button class="secondary" data-go="course">Browse all chapters</button></div></div><img src="'+esc(ch.cover)+'"></div><div class="tabs"><button class="tab" data-tab="learn">Learn</button><button class="tab" data-tab="words">Important words</button><button class="tab" data-tab="worksheet">Worksheet</button><button class="tab" data-tab="check">Knowledge check</button></div>'+tabContent(ch)+'</div>'}
    function tabContent(ch){if(state.tab==='words')return '<div class="card"><h2>Important words</h2><div class="glossary-grid">'+ch.vocabulary.map(function(v){return '<button class="glossary-item" data-term="'+esc(v.term)+'"><strong>'+esc(v.term)+'</strong><div class="muted">'+esc(v.definition||v.context||'Chapter vocabulary term')+'</div></button>'}).join('')+'</div></div>'; if(state.tab==='worksheet')return worksheet(ch); if(state.tab==='check')return check(ch); if(ch.number===2)return guided(ch); return '<div class="card"><h2>Chapter lesson</h2>'+ch.sections.map(function(s,i){var key=state.subject+'-'+ch.number+'-activity-'+i;return '<div class="lesson-block"><div class="eyebrow">Section '+esc(s.number)+'</div><h2>'+esc(s.title)+'</h2>'+(s.blocks||[]).slice(0,4).map(function(b){return '<p>'+esc(b)+'</p>'}).join('')+(i===0?'<img class="visual" src="'+esc(ch.visual)+'">':'')+'<div class="interaction"><strong>'+(state.subject==='biology'?'Science activity':'Map thinking activity')+'</strong><p>'+(state.subject==='biology'?'Make a prediction and explain the evidence.':'Use location, pattern, and place evidence to explain the idea.')+'</p><label class="activity-response"><span>Your answer</span><textarea data-activity="'+i+'" placeholder="Write your answer here.">'+esc(saved[key]||'')+'</textarea><small>Saved automatically.</small></label></div></div>'}).join('')+'</div>'}
    function guide(subject){return subject==='biology'?{big:'An ecosystem is a connected system where living things interact with each other and with nonliving conditions. Energy moves through feeding relationships while matter is recycled.',steps:[
      ['Ecosystems: living and nonliving parts','Ecology studies interactions among organisms and their environment. Biotic factors are living or once-living parts. Abiotic factors are nonliving conditions such as water, rocks, sunlight, temperature, and dissolved oxygen.','Sort pond parts into biotic and abiotic: fish, algae, water, rocks, sunlight, dissolved oxygen.','If water temperature rises, is that biotic or abiotic? How could it affect fish or algae?'],
      ['Ecological organization','One organism is one living thing. A population is the same species in one area. A community includes different populations. An ecosystem includes the community plus nonliving conditions.','Put these in order: ecosystem, organism, population, community.','Explain why coyotes plus rabbits plus grasses plus soil and water is an ecosystem.'],
      ['Habitat vs niche','Habitat means where an organism lives. Niche means how it lives there, gets food, uses resources, and interacts with other organisms.','Classify: A barn owl hunts mice at night. Habitat or niche?','Write one habitat statement and one niche statement for a frog, owl, or rabbit.'],
      ['Symbiosis','Mutualism means both benefit. Commensalism means one benefits and the other is mostly unaffected. Parasitism means one benefits and the host is harmed.','Classify tick on deer, orchid on tree, and ants with acacia.','Explain who benefits and who is harmed or unaffected in one example.'],
      ['Energy roles','Producers make their own food. Consumers get energy by eating other organisms. Herbivores, carnivores, omnivores, scavengers, and decomposers are different consumer roles.','Classify grass, rabbit, hawk, bear, vulture, and fungus.','Why are decomposers important for matter in ecosystems?'],
      ['Food chains and arrows','A food chain shows one pathway for energy and matter. Arrows point in the direction energy and matter move.','In grass -> grasshopper -> frog, what does grasshopper -> frog mean?','In grass -> rabbit -> fox, predict what may happen to foxes if rabbits decrease.'],
      ['Food webs and trophic levels','A food web shows many connected food chains. A trophic level is a feeding step. Producers form the base of an energy pyramid because they support higher levels.','Why is a food web more realistic than one food chain?','Explain why there are usually fewer top predators than producers.'],
      ['Energy flows, matter cycles','Energy flows through feeding relationships and is lost as heat. Matter cycles as water and nutrients are reused through living and nonliving parts.','Choose the correct idea: energy cycles forever OR energy flows while matter cycles.','Write the chapter idea in your own words.']
    ]}:{big:'Earth is made of interacting systems. Internal forces such as plate movement and external forces such as weathering and erosion reshape the planet, while water moves through Earth in a cycle.',steps:[
      ['Earth spheres','The hydrosphere is water, the lithosphere is land and rock, the atmosphere is air, and the biosphere is life. These spheres interact constantly.','Classify ocean, mountain, cloud-bearing air, and forest life.','Explain which spheres interact when rain falls on a mountain and plants absorb water.'],
      ['Inside Earth','Earth has a thin rocky crust, a thick hot mantle, and a hot dense core. Movement inside Earth helps shape the surface.','Label Earth layers from outside to inside.','Why do active layers beneath Earth matter?'],
      ['Plate tectonics','Earth’s crust is broken into moving plates. Plate tectonics explains mountains, ocean basins, earthquakes, and volcanoes.','What can moving plates create or cause?','Explain how slow movement can create major landforms over time.'],
      ['Plate interactions','Subduction means one plate sinks beneath another. Accretion adds material to a landmass. Spreading means plates move apart and new crust forms.','Match subduction, accretion, and spreading to the correct motion.','Choose one plate interaction and explain a feature it could create.'],
      ['Folds, faults, earthquakes, volcanoes','Pressure can bend rock into folds or break rock along faults. Sudden movement along a fault can cause an earthquake. Magma reaching the surface can form a volcano.','A break in rock where movement occurs is a fold or a fault?','Write a cause/effect chain for plate movement causing an earthquake.'],
      ['Weathering and erosion','Weathering breaks rock down. Erosion moves weathered material by water, wind, ice, or gravity.','A river carries sediment downstream. Weathering or erosion?','Classify a river valley, wind-blown sediment, glacier valley, and volcanic island as internal, external, or both.'],
      ['Earth water and the water cycle','Most surface water is salt water. Freshwater is limited and important. The water cycle moves water through evaporation, condensation, precipitation, runoff, and groundwater.','Put evaporation, condensation, and precipitation in order.','Why must a city planner think carefully about freshwater supply?'],
      ['Groundwater and Earth system challenge','Groundwater is water stored beneath Earth. An aquifer stores and carries groundwater. Earth systems interact in real places such as volcanic islands with rain, streams, rocks, and plants.','What is an aquifer?','Identify one internal force, one external force, one hydrosphere example, one lithosphere example, one biosphere example, and one system interaction.']
    ]}}
    function guided(ch){var g=guide(state.subject),idx=Math.max(0,Math.min(g.steps.length-1,Number(saved[state.subject+'-2-guide-step']||0))),s=g.steps[idx],done=g.steps.filter(function(_,i){return saved[state.subject+'-2-guide-done-'+i]}).length;return '<div class="card guided-start"><div class="eyebrow">Week 2 subject day</div><h2>'+esc(ch.title)+'</h2><p>'+esc(g.big)+'</p><div class="progress"><span style="width:'+Math.round(done/g.steps.length*100)+'%"></span></div><p class="muted">'+done+' of '+g.steps.length+' blocks complete. Work saves automatically.</p><div class="guide-pills">'+g.steps.map(function(_,i){return '<button class="'+(i===idx?'current ':'')+(saved[state.subject+'-2-guide-done-'+i]?'done':'')+'" data-guide-step="'+i+'">'+(i+1)+'</button>'}).join('')+'</div></div><div class="card guide-card"><div class="eyebrow">Block '+(idx+1)+' of '+g.steps.length+'</div><h2>'+esc(s[0])+'</h2><div class="guide-layout"><div><h3>Learn</h3><p>'+esc(s[1])+'</p><details class="guide-details"><summary>I do not get it</summary><p>First name the idea. Then match it to an example. Finally explain the evidence that proves it.</p></details><details class="guide-details"><summary>Tell me more</summary><p>Use the chapter vocabulary, but keep the answer short and connected to a real example.</p></details></div><div class="visual-box">'+s[1].split('.').slice(0,4).map(function(x){return x.trim()?'<span>'+esc(x.trim())+'</span>':''}).join('')+'</div></div><div class="interaction"><h3>Try</h3><p>'+esc(s[2])+'</p><label class="activity-response"><span>Your answer</span><textarea data-guide-answer="'+idx+'" placeholder="Write here. This saves automatically.">'+esc(saved[state.subject+'-2-guide-answer-'+idx]||'')+'</textarea><small>Saved automatically.</small></label><h3>Apply</h3><label class="activity-response"><span>'+esc(s[3])+'</span><textarea data-guide-apply="'+idx+'" placeholder="Use evidence from the lesson.">'+esc(saved[state.subject+'-2-guide-apply-'+idx]||'')+'</textarea><small>Saved automatically.</small></label></div><div class="actions"><button class="secondary" data-guide-step="'+Math.max(0,idx-1)+'">Previous block</button><button class="primary" data-guide-complete="'+idx+'">'+(idx===g.steps.length-1?'Save Week 2 work':'Complete block and continue')+'</button><button class="secondary" data-guide-step="'+Math.min(g.steps.length-1,idx+1)+'">Next block</button></div></div>'}
    function check(ch){if(ch.number===2){var g=guide(state.subject),qs=(state.subject==='biology'?['Classify rainfall as biotic or abiotic and explain why.','Put organism, population, community, ecosystem in order.','Explain habitat vs niche with one animal.','Classify bee/flower, orchid/tree, tick/deer by symbiosis.','In grass -> rabbit -> fox, what does rabbit -> fox mean?','Why is a food web more realistic than a food chain?','What is the difference between energy flow and matter cycling?']:['Classify ocean, mountain, air, and forest life by Earth sphere.','Name Earth layers from outside to inside.','What does plate tectonics explain?','Difference between subduction and spreading?','Freeze crack: weathering or erosion?','River carrying sediment: weathering or erosion?','Put evaporation, condensation, precipitation in order.','What is an aquifer and why does it matter?']);return '<div class="card"><h2>Knowledge check</h2><p class="muted">'+esc(g.big)+'</p>'+qs.map(function(q,i){return '<div class="worksheet-item"><strong>'+(i+1)+'. '+esc(q)+'</strong><textarea data-check="'+i+'">'+esc(saved[state.subject+'-2-check-'+i]||'')+'</textarea></div>'}).join('')+'</div>'}return '<div class="card"><h2>Knowledge check</h2>'+ch.knowledgeCheck.slice(0,8).map(function(q,i){return '<div class="worksheet-item"><strong>'+(i+1)+'. '+esc(q.prompt)+'</strong><textarea></textarea><div class="feedback">'+esc(q.answer)+'</div></div>'}).join('')+'</div>'}
    function worksheet(ch){var items=ch.number===2?fallbackWorksheetItems(ch):ch.worksheet.slice(0,14);return '<div class="card"><div class="actions"><button class="primary" data-export="blank">Export blank PDF</button><button class="primary" data-export="completed">Export completed PDF</button><button class="secondary" data-export="key">Parent answer key PDF</button><button class="secondary" onclick="window.print()">Print</button></div><h1>'+esc(course().name)+' Chapter '+ch.number+' Worksheet</h1><p>Student: Liam &nbsp; Grade: 9</p>'+items.map(function(q,i){return '<div class="worksheet-item"><div class="eyebrow">'+esc(q.type||'question')+'</div><strong>'+(i+1)+'. '+esc(q.prompt)+'</strong><textarea></textarea></div>'}).join('')+'</div>'}
    function fallbackWorksheetItems(ch){if(state.subject==='biology')return [
      {type:'Classification',prompt:'Sort fish, algae, insects, water, rocks, sunlight, and dissolved oxygen into biotic and abiotic.',answer:'Biotic: fish, algae, insects. Abiotic: water, rocks, sunlight, dissolved oxygen.'},
      {type:'Sequence',prompt:'Put organism, population, community, and ecosystem in order from smallest to largest.',answer:'Organism -> population -> community -> ecosystem.'},
      {type:'Match',prompt:'For a barn owl, match habitat and niche to: lives in grasslands/barns; hunts mice at night.',answer:'Habitat: grasslands/barns. Niche: hunts mice at night.'},
      {type:'Classification',prompt:'Classify ants/acacia, orchid/tree, and tick/deer as mutualism, commensalism, or parasitism.',answer:'Mutualism, commensalism, parasitism.'},
      {type:'Energy roles',prompt:'Classify grass, rabbit, hawk, bear, vulture, and fungus by ecosystem energy role.',answer:'Producer, herbivore, carnivore, omnivore, scavenger, decomposer.'},
      {type:'Food chain',prompt:'In Sun -> grass -> grasshopper -> frog -> snake -> hawk, identify the producer, first consumer, and meaning of grasshopper -> frog.',answer:'Producer grass; first consumer grasshopper; energy and matter move from grasshopper to frog.'},
      {type:'Scenario',prompt:'If rabbits decrease sharply in grass -> rabbit -> fox, predict one possible effect on foxes and explain why.',answer:'Foxes may decrease or change food source because rabbits are an energy/matter source.'},
      {type:'Explain',prompt:'Explain why energy flows through ecosystems but matter cycles.',answer:'Energy moves through feeding relationships and is lost as heat; matter is recycled.'}
    ];return [
      {type:'Classification',prompt:'Classify Pacific Ocean, mountain, cloud-bearing air, and forest life by Earth sphere.',answer:'Hydrosphere, lithosphere, atmosphere, biosphere.'},
      {type:'Diagram',prompt:'Label Earth layers from outside to inside.',answer:'Crust -> mantle -> core.'},
      {type:'Explain',prompt:'What does plate tectonics explain about Earth’s surface?',answer:'Moving plates shape continents, oceans, mountains, earthquakes, and volcanoes.'},
      {type:'Match',prompt:'Match subduction, accretion, and spreading with: one plate sinks; material is added; plates move apart.',answer:'Subduction: sinks; accretion: added material; spreading: plates apart.'},
      {type:'Classify',prompt:'A freeze crack in rock and a river carrying sediment: which is weathering and which is erosion?',answer:'Freeze crack is weathering; river carrying sediment is erosion.'},
      {type:'Sequence',prompt:'Put evaporation, condensation, and precipitation in order and describe each.',answer:'Evaporation -> condensation -> precipitation.'},
      {type:'Map thinking',prompt:'Explain why freshwater is limited even though much of Earth is covered by water.',answer:'Most water is salt water or not easily usable; accessible freshwater is limited.'},
      {type:'Earth system challenge',prompt:'For a rainy volcanic island, identify one internal force, one external force, one hydrosphere example, one lithosphere example, one biosphere example, and one interaction.',answer:'Volcano/internal; rain/streams erosion external; water hydrosphere; mountain/rock lithosphere; plants biosphere; water interacts with rock/plants.'}
    ]}
    function parent(){var inv=window.__LIAM_CURRICULUM_INVENTORY__;var inventory=''; if(inv){inventory='<div class="card"><h1>Course Completeness</h1><div class="grid">'+inventoryCourse(inv.biology)+inventoryCourse(inv.geography)+'</div><h2>Supplemental files</h2><div class="inventory-list">'+inv.supplemental.map(function(item){return '<article><strong>'+esc(item.name)+'</strong><span class="'+(item.status==='SOURCE_FOUND'?'ok':'bad')+'">'+esc(item.status)+'</span><small>'+esc(item.file||'')+'</small><code>'+(item.hash?esc(item.hash.slice(0,16))+'...':'no hash')+'</code></article>'}).join('')+'</div></div>'} var rows=[]; Object.keys(data).forEach(function(id){data[id].chapters.forEach(function(ch){rows.push('<tr><td>'+esc(data[id].name)+'</td><td>'+ch.number+'</td><td>'+esc(ch.title)+'</td><td>SOURCE_FOUND, PARSED, GENERATED, RENDERED, VALIDATED</td></tr>')})}); rows.push('<tr><td>Biology</td><td>16</td><td>Unavailable</td><td>UNAVAILABLE - intentionally excluded</td></tr>'); return '<div class="wrap">'+inventory+'<div class="card"><h1>Parent curriculum inspector</h1><table style="width:100%"><tbody>'+rows.join('')+'</tbody></table></div></div>'}
    function inventoryCourse(course){return '<section class="inventory-course"><h2>'+esc(course.label)+'</h2><p>'+course.availableSourceChapters+' source chapters - '+course.parsed+' parsed - '+course.rendered+' rendered - '+course.validated+' validated - '+(course.intentionallyUnavailable||0)+' unavailable - '+course.unaccounted+' unaccounted</p><div class="inventory-list">'+course.chapters.map(function(row){return '<article><strong>Chapter '+row.chapter+': '+esc(row.title)+'</strong><span>'+row.statuses.map(function(status){return '<b class="'+(status==='FAILED'||status==='MISSING'?'bad':status==='UNAVAILABLE'?'warn':'ok')+'">'+esc(status)+'</b>'}).join(' ')+'</span><small>'+esc(row.sourceFile||row.note||'')+'</small><code>'+(row.hash?esc(row.hash.slice(0,16))+'...':'no hash')+'</code></article>'}).join('')+'</div></section>'}
    function render(){app.innerHTML=top()+(state.view==='home'?home():state.view==='course'?coursePage():state.view==='parent'?parent():chapterPage())}
    app.addEventListener('input',function(e){if(e.target.dataset.activity!==undefined){saved[state.subject+'-'+state.chapter+'-activity-'+e.target.dataset.activity]=e.target.value; save()} if(e.target.dataset.guideAnswer!==undefined){saved[state.subject+'-2-guide-answer-'+e.target.dataset.guideAnswer]=e.target.value; save()} if(e.target.dataset.guideApply!==undefined){saved[state.subject+'-2-guide-apply-'+e.target.dataset.guideApply]=e.target.value; save()} if(e.target.dataset.check!==undefined){saved[state.subject+'-2-check-'+e.target.dataset.check]=e.target.value; save()}});
    app.addEventListener('click',function(e){var t=e.target.closest('[data-subject],[data-week2],[data-guide-step],[data-guide-complete],[data-chapter],[data-tab],[data-go],[data-term],[data-export]'); if(!t)return; if(t.dataset.week2){state.subject=t.dataset.week2; state.view='chapter'; state.chapter=2; state.tab='learn'} else if(t.dataset.subject){state.subject=t.dataset.subject; state.view='course'; state.chapter=course().chapters[0].number; state.tab='learn'} if(t.dataset.guideStep!==undefined){state.view='chapter'; state.chapter=2; state.tab='learn'; saved[state.subject+'-2-guide-step']=Number(t.dataset.guideStep); save()} if(t.dataset.guideComplete!==undefined){var gi=Number(t.dataset.guideComplete),g=guide(state.subject); saved[state.subject+'-2-guide-done-'+gi]=true; saved[state.subject+'-2-evidence-'+gi]=new Date().toISOString(); if(gi<g.steps.length-1)saved[state.subject+'-2-guide-step']=gi+1; save()} if(t.dataset.chapter){state.chapter=Number(t.dataset.chapter); state.view='chapter'; state.tab='learn'} if(t.dataset.tab){state.tab=t.dataset.tab} if(t.dataset.go==='home'){state.view='home'} if(t.dataset.go==='course'){state.view='course'} if(t.dataset.go==='parent'){state.view='parent'} if(t.dataset.term){alert(t.dataset.term);return} if(t.dataset.export){var ch=chapter(),items=ch.number===2?fallbackWorksheetItems(ch):ch.worksheet.slice(0,14); var lines=[course().name+' Chapter '+ch.number+' '+(t.dataset.export==='key'?'Answer Key':'Worksheet'), ch.title, 'Student: Liam Grade: 9']; items.forEach(function(q,i){lines.push((i+1)+'. '+q.prompt); if(t.dataset.export==='key')lines.push('Answer: '+q.answer); else lines.push('____________________________','____________________________')}); download(pdfBlob(lines),'Liam_'+state.subject+'_Chapter_'+String(ch.number).padStart(2,'0')+'_'+t.dataset.export+'.pdf');return} nav()});
    window.addEventListener('popstate',function(){applyRoute();render()});
    applyRoute(); nav(true);
  }
  setTimeout(bootFallback,500);
})();
