(function(){
  function esc(value){return String(value||'').replace(/[&<>"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
  function pdfClean(value){return String(value||'').normalize('NFKD').replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/\u2192/g,'->').replace(/\u2022/g,'-').replace(/\u00A0/g,' ').replace(/[^\x09\x0A\x0D\x20-\x7E]/g,'')}
  function pdfEscape(value){return pdfClean(value).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
  function pdfBlob(lines){
    var encoder=new TextEncoder(), wrapped=[]; function byteLen(s){return encoder.encode(s).length}
    lines.forEach(function(line){line=pdfClean(line); if(!line){wrapped.push(''); return} while(line.length>86){var cut=line.lastIndexOf(' ',86); if(cut<30)cut=86; wrapped.push(line.slice(0,cut)); line=line.slice(cut).trim()} wrapped.push(line)});
    var pages=[]; for(var i=0;i<wrapped.length;i+=48)pages.push(wrapped.slice(i,i+48)); if(!pages.length)pages=[['']];
    var objs=[]; function add(s){objs.push(s); return objs.length}
    var font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'), pageIds=[], contentIds=[];
    pages.forEach(function(pg){var stream='BT /F1 11 Tf 48 744 Td 15 TL '; pg.forEach(function(l){stream+='('+pdfEscape(l)+') Tj T* '}); stream+='ET'; contentIds.push(add('<< /Length '+byteLen(stream)+' >>\nstream\n'+stream+'\nendstream')); pageIds.push(add('PLACEHOLDER'))});
    var pagesId=add('PLACEHOLDER'); pageIds.forEach(function(pid,i){objs[pid-1]='<< /Type /Page /Parent '+pagesId+' 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 '+font+' 0 R >> >> /Contents '+contentIds[i]+' 0 R >>'}); objs[pagesId-1]='<< /Type /Pages /Count '+pageIds.length+' /Kids ['+pageIds.map(function(x){return x+' 0 R'}).join(' ')+'] >>';
    var catalog=add('<< /Type /Catalog /Pages '+pagesId+' 0 R >>'), parts=[], offs=[0], pos=0; function push(s){parts.push(s); pos+=byteLen(s)}
    push('%PDF-1.4\n'); objs.forEach(function(o,i){offs.push(pos); push((i+1)+' 0 obj\n'+o+'\nendobj\n')}); var xref=pos; push('xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n'); for(var j=1;j<offs.length;j++)push(String(offs[j]).padStart(10,'0')+' 00000 n \n'); push('trailer << /Size '+(objs.length+1)+' /Root '+catalog+' 0 R >>\nstartxref\n'+xref+'\n%%EOF'); return new Blob(parts,{type:'application/pdf'});
  }
  function download(blob,name){var url=URL.createObjectURL(blob); var preview=window.open(url,'_blank','noopener'); var a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); if(!preview)alert('PDF exported. If you do not see it, check your Downloads folder.'); setTimeout(function(){URL.revokeObjectURL(url); a.remove()},120000)}
  function bootFallback(){
    var app=document.getElementById('app');
    if(!app || !/Loading Liam Learning|App startup error/.test(app.textContent||''))return;
    var data=window.__LIAM_COURSE_DATA__;
    if(!data){app.innerHTML='<div class="wrap"><div class="card"><h1>Course data did not load</h1></div></div>'; return}
    var state={subject:'biology', view:'home', chapter:1, tab:'learn'}, saved={};
    try{saved=JSON.parse(localStorage.getItem('liam-progress')||'{}')||{}}catch(e){saved={}}
    function save(){localStorage.setItem('liam-progress',JSON.stringify(saved))}
    function route(){if(state.view==='home')return '#home'; if(state.view==='course')return '#course/'+state.subject; if(state.view==='chapter')return '#chapter/'+state.subject+'/'+state.chapter+'/'+state.tab; if(state.view==='parent')return '#parent'; return '#home'}
    function applyRoute(){var p=(location.hash||'#home').replace(/^#/,'').split('/').filter(Boolean); if(p[0]==='course'&&data[p[1]]){state.view='course'; state.subject=p[1]; state.chapter=course().chapters[0].number; return} if(p[0]==='chapter'&&data[p[1]]){state.view='chapter'; state.subject=p[1]; state.chapter=Number(p[2])||course().chapters[0].number; state.tab=p[3]||'learn'; return} if(p[0]==='parent'){state.view='parent'; return} state.view='home'}
    function nav(replace){var r=route(); if(location.hash!==r)history[replace?'replaceState':'pushState']({view:state.view,subject:state.subject,chapter:state.chapter,tab:state.tab},'',r); render()}
    function course(){return data[state.subject]}
    function chapter(){return course().chapters.find(function(c){return c.number==state.chapter})||course().chapters[0]}
    function top(){return '<div class="top"><div class="brand">Liam Learning</div><button class="navbtn" data-go="home">Home</button><button class="navbtn" data-subject="biology">Biology</button><button class="navbtn" data-subject="geography">World Geography</button><button class="navbtn" data-go="parent">Parent</button></div>'}
    function home(){return '<div class="wrap"><div class="today"><div class="eyebrow" style="color:#9dd8c8">One subject at a time</div><div class="h1">Today can stay small.</div><p class="muted">Choose one course. Learn in short blocks. Stop when the learning is done.</p></div><div class="grid"><div class="card subject bio"><h2>Biology</h2><p>'+data.biology.chapters.length+' chapters available. Chapter 16 is unavailable.</p><button class="primary" data-subject="biology">Open Biology</button></div><div class="card subject geo"><h2>World Geography</h2><p>'+data.geography.chapters.length+' chapters available.</p><button class="primary" data-subject="geography">Open World Geography</button></div></div></div>'}
    function coursePage(){var c=course(); return '<div class="wrap"><div class="hero"><div><div class="eyebrow">'+esc(c.name)+'</div><div class="h1">Course map</div><p class="muted">Every supplied chapter is visible and openable.</p></div><img src="'+esc(c.chapters[0].cover)+'"></div><div class="card" style="margin-top:18px"><div class="chapter-list">'+c.chapters.map(function(ch){return '<button class="chapter-link" data-chapter="'+ch.number+'"><strong>Chapter '+ch.number+'</strong><small>'+esc(ch.title)+'</small><small>'+ch.sections.length+' sections - '+ch.vocabulary.length+' words - '+ch.worksheet.length+' worksheet items</small></button>'}).join('')+'</div></div></div>'}
    function termButton(term){return '<button class="term" data-term="'+esc(term)+'">'+esc(term)+'</button>'}
    function chapterPage(){var ch=chapter(), c=course(); return '<div class="wrap"><div class="hero"><div><div class="eyebrow">'+esc(c.name)+' - Chapter '+ch.number+'</div><div class="h1">'+esc(ch.title)+'</div><p class="muted">Learn here. The PDF is reference material only.</p><div class="chapter-jump"><button class="secondary" data-go="course">Browse all chapters</button></div></div><img src="'+esc(ch.cover)+'"></div><div class="tabs"><button class="tab" data-tab="learn">Learn</button><button class="tab" data-tab="words">Important words</button><button class="tab" data-tab="worksheet">Worksheet</button><button class="tab" data-tab="check">Knowledge check</button></div>'+tabContent(ch)+'</div>'}
    function tabContent(ch){if(state.tab==='words')return '<div class="card"><h2>Important words</h2><div class="glossary-grid">'+ch.vocabulary.map(function(v){return '<button class="glossary-item" data-term="'+esc(v.term)+'"><strong>'+esc(v.term)+'</strong><div class="muted">'+esc(v.definition||v.context||'Chapter vocabulary term')+'</div></button>'}).join('')+'</div></div>'; if(state.tab==='worksheet')return worksheet(ch); if(state.tab==='check')return '<div class="card"><h2>Knowledge check</h2>'+ch.knowledgeCheck.slice(0,8).map(function(q,i){return '<div class="worksheet-item"><strong>'+(i+1)+'. '+esc(q.prompt)+'</strong><textarea></textarea><div class="feedback">'+esc(q.answer)+'</div></div>'}).join('')+'</div>'; return '<div class="card"><h2>Chapter lesson</h2>'+ch.sections.map(function(s,i){var key=state.subject+'-'+ch.number+'-activity-'+i;return '<div class="lesson-block"><div class="eyebrow">Section '+esc(s.number)+'</div><h2>'+esc(s.title)+'</h2>'+(s.blocks||[]).slice(0,4).map(function(b){return '<p>'+esc(b)+'</p>'}).join('')+(i===0?'<img class="visual" src="'+esc(ch.visual)+'">':'')+'<div class="interaction"><strong>'+(state.subject==='biology'?'Science activity':'Map thinking activity')+'</strong><p>'+(state.subject==='biology'?'Make a prediction and explain the evidence.':'Use location, pattern, and place evidence to explain the idea.')+'</p><label class="activity-response"><span>Your answer</span><textarea data-activity="'+i+'" placeholder="Write your answer here.">'+esc(saved[key]||'')+'</textarea><small>Saved automatically.</small></label></div></div>'}).join('')+'</div>'}
    function worksheet(ch){return '<div class="card"><div class="actions"><button class="primary" data-export="blank">Export blank PDF</button><button class="primary" data-export="completed">Export completed PDF</button><button class="secondary" data-export="key">Parent answer key PDF</button><button class="secondary" onclick="window.print()">Print</button></div><h1>'+esc(course().name)+' Chapter '+ch.number+' Worksheet</h1><p>Student: Liam &nbsp; Grade: 9</p>'+ch.worksheet.slice(0,14).map(function(q,i){return '<div class="worksheet-item"><div class="eyebrow">'+esc(q.type||'question')+'</div><strong>'+(i+1)+'. '+esc(q.prompt)+'</strong><textarea></textarea></div>'}).join('')+'</div>'}
    function parent(){var inv=window.__LIAM_CURRICULUM_INVENTORY__;var inventory=''; if(inv){inventory='<div class="card"><h1>Course Completeness</h1><div class="grid">'+inventoryCourse(inv.biology)+inventoryCourse(inv.geography)+'</div><h2>Supplemental files</h2><div class="inventory-list">'+inv.supplemental.map(function(item){return '<article><strong>'+esc(item.name)+'</strong><span class="'+(item.status==='SOURCE_FOUND'?'ok':'bad')+'">'+esc(item.status)+'</span><small>'+esc(item.file||'')+'</small><code>'+(item.hash?esc(item.hash.slice(0,16))+'...':'no hash')+'</code></article>'}).join('')+'</div></div>'} var rows=[]; Object.keys(data).forEach(function(id){data[id].chapters.forEach(function(ch){rows.push('<tr><td>'+esc(data[id].name)+'</td><td>'+ch.number+'</td><td>'+esc(ch.title)+'</td><td>SOURCE_FOUND, PARSED, GENERATED, RENDERED, VALIDATED</td></tr>')})}); rows.push('<tr><td>Biology</td><td>16</td><td>Unavailable</td><td>UNAVAILABLE - intentionally excluded</td></tr>'); return '<div class="wrap">'+inventory+'<div class="card"><h1>Parent curriculum inspector</h1><table style="width:100%"><tbody>'+rows.join('')+'</tbody></table></div></div>'}
    function inventoryCourse(course){return '<section class="inventory-course"><h2>'+esc(course.label)+'</h2><p>'+course.availableSourceChapters+' source chapters - '+course.parsed+' parsed - '+course.rendered+' rendered - '+course.validated+' validated - '+(course.intentionallyUnavailable||0)+' unavailable - '+course.unaccounted+' unaccounted</p><div class="inventory-list">'+course.chapters.map(function(row){return '<article><strong>Chapter '+row.chapter+': '+esc(row.title)+'</strong><span>'+row.statuses.map(function(status){return '<b class="'+(status==='FAILED'||status==='MISSING'?'bad':status==='UNAVAILABLE'?'warn':'ok')+'">'+esc(status)+'</b>'}).join(' ')+'</span><small>'+esc(row.sourceFile||row.note||'')+'</small><code>'+(row.hash?esc(row.hash.slice(0,16))+'...':'no hash')+'</code></article>'}).join('')+'</div></section>'}
    function render(){app.innerHTML=top()+(state.view==='home'?home():state.view==='course'?coursePage():state.view==='parent'?parent():chapterPage())}
    app.addEventListener('input',function(e){if(e.target.dataset.activity!==undefined){saved[state.subject+'-'+state.chapter+'-activity-'+e.target.dataset.activity]=e.target.value; save()}});
    app.addEventListener('click',function(e){var t=e.target.closest('[data-subject],[data-chapter],[data-tab],[data-go],[data-term],[data-export]'); if(!t)return; if(t.dataset.subject){state.subject=t.dataset.subject; state.view='course'; state.chapter=course().chapters[0].number; state.tab='learn'} if(t.dataset.chapter){state.chapter=Number(t.dataset.chapter); state.view='chapter'; state.tab='learn'} if(t.dataset.tab){state.tab=t.dataset.tab} if(t.dataset.go==='home'){state.view='home'} if(t.dataset.go==='course'){state.view='course'} if(t.dataset.go==='parent'){state.view='parent'} if(t.dataset.term){alert(t.dataset.term);return} if(t.dataset.export){var ch=chapter(); var lines=[course().name+' Chapter '+ch.number+' '+(t.dataset.export==='key'?'Answer Key':'Worksheet'), ch.title, 'Student: Liam Grade: 9']; ch.worksheet.slice(0,14).forEach(function(q,i){lines.push((i+1)+'. '+q.prompt); if(t.dataset.export==='key')lines.push('Answer: '+q.answer); else lines.push('____________________________')}); download(pdfBlob(lines),'Liam_'+state.subject+'_Chapter_'+String(ch.number).padStart(2,'0')+'_'+t.dataset.export+'.pdf');return} nav()});
    window.addEventListener('popstate',function(){applyRoute();render()});
    applyRoute(); nav(true);
  }
  setTimeout(bootFallback,500);
})();
