(()=>{
'use strict';
const KEY='devries-sat-prep-v1';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}};
const store=load(); const save=()=>localStorage.setItem(KEY,JSON.stringify(store));
const students={liam:'Liam',leilani:'Leilani'};
const math=[
 {d:'Geometry',q:'A point (x,y) is 10 units from the origin. Which point could it be?',o:['(6,8)','(4,8)','(5,6)','(2,9)'],a:0,h:'Use x²+y²=d².',e:'6²+8²=36+64=100, so the distance is 10.'},
 {d:'Functions',q:'A graph rises from local minimum A to local maximum B, then falls to local minimum C. Which statements must be true?',o:['Increasing everywhere y>0','Increasing A to B only','Increasing A to B and decreasing B to C','Decreasing A to B'],a:2,h:'Increasing means y rises as x moves right.',e:'From A to B the graph rises; from B to C it falls. The sign of y does not determine increasing/decreasing.'},
 {d:'Advanced Algebra',q:'If xy=12 and x−y=5, what is x²+y²?',o:['25','49','73','169'],a:2,h:'Square x−y and use xy.',e:'(x−y)²=x²−2xy+y². So 25=x²+y²−24, giving 49. Correction check: x²+y²=49.'],
 {d:'Advanced Algebra',q:'If −1<x<0, which ordering is correct?',o:['x<x³<x²','x³<x<x²','x²<x³<x','x<x²<x³'],a:0,h:'Test a convenient value such as −1/2.',e:'At x=−1/2: x=−0.5, x³=−0.125, x²=0.25, so x<x³<x².'},
 {d:'Linear Equations',q:'Solve: (5/3)(x−4) − (11/6)(x−4) = 7/2.',o:['−17','−10','10','25'],a:0,h:'Factor out (x−4), then combine the fractions.',e:'5/3−11/6=10/6−11/6=−1/6. Thus −(x−4)/6=7/2, so x−4=−21 and x=−17.'},
 {d:'Geometry',q:'A right triangular prism has volume 480 cm³, prism length 20 cm, and one perpendicular base leg 8 cm. Find the other base leg x.',o:['3','6','12','24'],a:1,h:'V=(1/2·8·x)(20).',e:'480=80x, so x=6.'},
 {d:'Ratios',q:'Two people contribute $60 and $40 toward tickets and split a $500 prize in the same ratio. How much does the second person receive?',o:['$100','$200','$250','$300'],a:1,h:'The second contribution is 40/(60+40) of the total.',e:'40/100=0.4 and 0.4×500=$200.'},
 {d:'Ratios',q:'3/7 of the managers at a company are women. If 36 managers are women, how many managers are there total?',o:['48','72','84','108'],a:2,h:'Set (3/7)T=36.',e:'T=36×7/3=84.'},
 {d:'Linear Equations',q:'A line satisfies kx−3y=18 and passes through (6,2). Find k.',o:['2','3','4','6'],a:2,h:'Substitute x=6 and y=2.',e:'6k−6=18, so 6k=24 and k=4.'},
 {d:'Exponents',q:'For f(x)=3^(2x−1)−27, find x when f(x)=0.',o:['1','2','3','4'],a:1,h:'Rewrite 27 as a power of 3.',e:'3^(2x−1)=27=3³, so 2x−1=3 and x=2.'}
];
// fix the deliberately recalculated identity item before rendering
math[2]={d:'Advanced Algebra',q:'If xy=12 and x−y=5, what is x²+y²?',o:['25','49','73','169'],a:1,h:'Square x−y and use xy.',e:'(x−y)²=x²−2xy+y². So 25=x²+y²−24, giving x²+y²=49.'};
const rw=[
 {d:'Reading & Writing',q:'A passage gives evidence that directly supports a researcher’s claim. What should you prioritize?',o:['The most dramatic detail','The evidence most directly tied to the claim','The longest quotation','Background information'],a:1,h:'SAT evidence questions reward relevance, not drama.',e:'Choose the evidence that most directly proves the stated claim.'},
 {d:'Grammar',q:'Which choice best joins two independent clauses?',o:['Comma only','Semicolon','No punctuation','Apostrophe'],a:1,h:'Both sides can stand alone as sentences.',e:'A semicolon can correctly join closely related independent clauses.'},
 {d:'Transitions',q:'The second sentence contrasts with the first. Which transition best signals that relationship?',o:['Similarly','Therefore','However','For example'],a:2,h:'Look for a contrast word.',e:'“However” signals contrast.'}
];
function state(student){store[student]??={};return store[student]}
function card(item,i,student,type){const id=type+'-'+i,s=state(student),picked=s[id];return `<article class="satq"><div class="satdomain">${item.d}</div><h4>${i+1}. ${item.q}</h4><div class="satopts">${item.o.map((x,j)=>`<label><input type="radio" name="${student}-${id}" value="${j}" ${Number(picked)===j?'checked':''}> <span>${x}</span></label>`).join('')}</div><div class="satactions"><button data-check="${type}|${i}">Check My Answer</button><button data-hint="${type}|${i}">Hint</button></div><div class="satfb" data-fb="${type}|${i}"></div></article>`}
function render(student='liam',tab='math'){
 let root=document.getElementById('sat-prep-overlay'); if(root)root.remove();
 const bank=tab==='math'?math:rw, s=state(student); const done=Object.keys(s).filter(k=>k.startsWith(tab+'-')).length;
 document.body.insertAdjacentHTML('beforeend',`<div id="sat-prep-overlay" class="satover"><div class="satshell"><header><div><div class="satkicker">Digital SAT Prep Center</div><h2>${students[student]} · targeted practice</h2><p>Built around the trouble patterns from the practice SAT screenshots. Practice baseline: 1070–1090.</p></div><button data-close>Close</button></header><nav><button data-student="liam" class="${student==='liam'?'on':''}">Liam</button><button data-student="leilani" class="${student==='leilani'?'on':''}">Leilani</button><span></span><button data-tab="math" class="${tab==='math'?'on':''}">Math Focus</button><button data-tab="rw" class="${tab==='rw'?'on':''}">Reading & Writing</button></nav><main><section class="satintro"><h3>${tab==='math'?'Math trouble-area training':'Reading & Writing foundation'}</h3><p>${tab==='math'?'Focus: coordinate distance, function behavior, algebraic identities, negative powers, linear equations, geometry/volume, ratios, proportions, and exponents.':'Short foundation drills now; this section can expand from their Reading & Writing score report and missed questions.'}</p><div class="satprogress">Saved responses: ${done}/${bank.length}</div></section>${bank.map((q,i)=>card(q,i,student,tab)).join('')}<section class="sattools"><button data-reset>Reset This Drill</button><button data-export>Export SAT Practice</button></section></main></div></div>`);
 root=document.getElementById('sat-prep-overlay'); root.querySelector('[data-close]').onclick=()=>root.remove();
 root.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>render(b.dataset.student,tab)); root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>render(student,b.dataset.tab));
 root.querySelectorAll('input[type=radio]').forEach(r=>r.onchange=()=>{s[r.name.split('-').slice(1).join('-')]=Number(r.value);save()});
 root.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const [t,n]=b.dataset.check.split('|'),item=(t==='math'?math:rw)[+n],id=t+'-'+n,fb=root.querySelector(`[data-fb="${t}|${n}"]`),v=s[id];if(v===undefined){fb.className='satfb show warn';fb.textContent='Choose an answer first.';return}fb.className='satfb show '+(Number(v)===item.a?'good':'bad');fb.innerHTML=Number(v)===item.a?`✓ Correct. ${item.e}`:`Not yet. ${item.h} Try again before using the explanation.`;});
 root.querySelectorAll('[data-hint]').forEach(b=>b.onclick=()=>{const [t,n]=b.dataset.hint.split('|'),item=(t==='math'?math:rw)[+n],fb=root.querySelector(`[data-fb="${t}|${n}"]`);fb.className='satfb show hint';fb.textContent='Hint: '+item.h});
 root.querySelector('[data-reset]').onclick=()=>{if(confirm('Reset saved answers for this drill?')){Object.keys(s).filter(k=>k.startsWith(tab+'-')).forEach(k=>delete s[k]);save();render(student,tab)}};
 root.querySelector('[data-export]').onclick=()=>{const rows=bank.map((q,i)=>({q,choice:s[tab+'-'+i]}));const w=window.open('','_blank');if(!w){alert('Allow pop-ups to export.');return}const esc=x=>String(x??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));w.document.write(`<title>${students[student]} SAT Practice</title><style>body{font:14px Arial;margin:36px;line-height:1.45}h1{font-size:22px}.q{margin:18px 0;break-inside:avoid}.ans{padding:8px;border:1px solid #ccc}</style><h1>${students[student]} · SAT ${tab==='math'?'Math':'Reading & Writing'} Practice</h1>${rows.map((r,i)=>`<div class=q><b>${i+1}. ${esc(r.q.q)}</b><div class=ans>Response: ${r.choice===undefined?'No response':esc(r.q.o[r.choice])}</div></div>`).join('')}<script>onload=()=>setTimeout(()=>print(),100)<\/script>`);w.document.close()};
 }
 function inject(){if(document.getElementById('sat-prep-launch'))return;const b=document.createElement('button');b.id='sat-prep-launch';b.textContent='SAT Prep';b.onclick=()=>render((window.S&&S.student)||'liam','math');document.body.appendChild(b)}
 const css=document.createElement('style');css.textContent=`#sat-prep-launch{position:fixed;right:18px;bottom:18px;z-index:9000;border:0;border-radius:999px;padding:12px 18px;background:#172f49;color:white;font-weight:800;box-shadow:0 4px 18px #0003}.satover{position:fixed;inset:0;z-index:100000;background:#14202ddd;padding:12px}.satshell{height:100%;max-width:1100px;margin:auto;background:#f6f8fa;border-radius:16px;overflow:hidden;display:flex;flex-direction:column}.satshell header{background:white;padding:16px 20px;display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid #ddd}.satshell h2{margin:3px 0}.satshell p{margin:4px 0;color:#53606c}.satkicker{font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.satshell header button,.satshell nav button,.satactions button,.sattools button{border:1px solid #aeb8c2;border-radius:8px;background:white;padding:9px 12px;font-weight:700}.satshell nav{padding:10px 18px;background:white;display:flex;gap:8px;flex-wrap:wrap}.satshell nav span{flex:1}.satshell nav .on{background:#172f49;color:white}.satshell main{overflow:auto;padding:18px;max-width:850px;width:100%;margin:auto}.satintro,.satq,.sattools{background:white;border:1px solid #dbe1e6;border-radius:12px;padding:16px;margin-bottom:14px}.satdomain{font-size:12px;font-weight:800;text-transform:uppercase;color:#53606c}.satq h4{font-size:16px;margin:7px 0 12px}.satopts{display:grid;gap:7px}.satopts label{padding:9px;border:1px solid #e1e5e8;border-radius:8px}.satactions{display:flex;gap:8px;margin-top:12px}.satfb{display:none}.satfb.show{display:block;margin-top:10px;padding:10px;border-radius:8px}.satfb.good{background:#e9f7ee}.satfb.bad,.satfb.warn{background:#fff0ed}.satfb.hint{background:#eef5fb}.sattools{display:flex;justify-content:space-between;gap:8px}.satprogress{font-weight:700;margin-top:8px}@media(max-width:650px){.satover{padding:0}.satshell{border-radius:0}.satshell nav span{display:none}.satshell main{padding:10px}.sattools{flex-direction:column}}`;document.head.appendChild(css);
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();